import { type ConfigSettingDefinition, intRange, numRange, port } from './schema-shared.js';

export const coreConfigDefaults = {
  display: {
    stream: true,
    lineNumbers: 'off',
    collapseThreshold: 30,
    theme: 'vaporwave',
    showThinking: false,
    showReasoningSummary: false,
    showTokenSpeed: false,
    showToolPreview: false,
  },
  provider: {
    reasoningEffort: 'medium',
    model: 'openrouter:openrouter/free',
    embeddingProvider: 'hashed-local',
    systemPromptFile: '',
    optimizerMode: 'off',
    optimizerPinnedModel: '',
    localContextIngestion: true,
  },
  behavior: {
    autoApprove: false,
    autoCompactThreshold: 80,
    compactionStrategy: 'structured',
    staleContextWarnings: true,
    saveHistory: true,
    notifyOnComplete: true,
    suggestAlternativeOnProviderFail: false,
    hitlMode: 'balanced',
    toolResultReconciliation: 'reconcile',
    returnContextMode: 'off',
    guidanceMode: 'minimal',
  },
  storage: {
    secretPolicy: 'preferred_secure',
    artifacts: {
      maxBytes: 512 * 1024 * 1024,
    },
  },
  permissions: {
    mode: 'prompt',
    backgroundAgents: 'inherit',
    engine: 'baseline',
    simulation: true,
    divergenceDashboard: true,
    commandParser: 'ast',
    divergenceThreshold: 0.05,
    maxDivergenceRecords: 500,
    tools: {
      read: 'allow',
      write: 'prompt',
      edit: 'prompt',
      exec: 'prompt',
      find: 'allow',
      fetch: 'prompt',
      analyze: 'allow',
      inspect: 'allow',
      agent: 'prompt',
      state: 'allow',
      workflow: 'prompt',
      registry: 'allow',
      delegate: 'prompt',
      mcp: 'prompt',
    },
  },
  diagnostics: {
    postEdit: 'on',
  },
  orchestration: {
    recursionEnabled: false,
    maxDepth: 0,
  },
  planner: {
    decomposition: 'agent',
    maxTurns: 6,
    tokenCeiling: 120_000,
    wallTimeoutMs: 120_000, // 60s starved reasoning models that think silently before emitting (live replay: planner hit the wall at Turn 3 and fell back)
    adaptive: false,
  },
  sandbox: {
    enabled: true,
    judgment: 'annotate',
    egressAllowlist: [] as string[],
    workspaceWritable: [] as string[],
    replIsolation: 'shared-vm',
    mcpIsolation: 'disabled',
    windowsMode: 'native-basic',
    vmBackend: 'local',
    qemuBinary: 'qemu-system-x86_64',
    qemuImagePath: '',
    qemuExecWrapper: '',
    qemuGuestHost: '',
    qemuGuestPort: 2222,
    qemuGuestUser: 'goodvibes',
    qemuWorkspacePath: '/workspace',
    qemuSessionMode: 'attach',
    replJavaScriptCommand: 'bun',
  },
  ui: {
    voiceEnabled: false,
    systemMessages: 'panel',
    operationalMessages: 'panel',
    wrfcMessages: 'both',
  },
  tts: {
    provider: 'elevenlabs',
    voice: '',
    llmProvider: '',
    llmModel: '',
    speed: 1.0,
  },
  release: {
    channel: 'stable',
  },
  daemon: {
    enabled: true,
    embedInProcess: false,
  },
  danger: {
    httpListener: false,
  },
  tools: {
    llmEnabled: false,
    llmProvider: '',
    llmModel: '',
    autoHeal: false,
    defaultTokenBudget: 5000,
    hooksFile: 'hooks.json',
    overflowSpillBackend: 'file',
    contractVerification: true,
    outputSchemaFingerprints: false,
  },
  wrfc: {
    scoreThreshold: 9.9,
    maxFixAttempts: 5,
    autoCommit: true,
    commitScope: 'scoped',
    agentHeartbeatTimeoutMs: 0,
    transportRetryLimit: 1,
    transportRetryDelayMs: 5000,
    gates: [
      { name: 'typecheck', command: 'npx tsc --noEmit', enabled: true },
      { name: 'lint', command: 'npx eslint . --max-warnings 0', enabled: true },
      { name: 'build', command: 'npm run build', enabled: false },
    ],
  },
  cache: {
    enabled: true,
    stableTtl: '1h',
    monitorHitRate: true,
    hitRateWarningThreshold: 0.3,
  },
  helper: {
    enabled: false,
    globalProvider: '',
    globalModel: '',
  },
  notifications: {
    webhookUrls: [],
    adaptiveSuppression: true,
    burstWindowMs: 1_000,
    burstThreshold: 3,
    burstCooldownMs: 3_000,
    pushApproval: true,
    pushNeedsInput: true,
    pushCompletion: true,
    blockedEscalationGraceMs: 5 * 60 * 1000,
    blockedEscalationFollowUpMs: 5 * 60 * 1000,
    blockedEscalationMaxFollowUps: 2,
  },
};

export const coreHeadConfigSettings: ConfigSettingDefinition[] = [
  {
    key: 'display.stream',
    type: 'boolean',
    default: true,
    description: 'Stream LLM tokens as they arrive',
  },
  {
    key: 'display.lineNumbers',
    type: 'enum',
    default: 'off',
    description: 'Show line numbers for all assistant output, code blocks only, or not at all',
    enumValues: ['all', 'code', 'off'],
  },
  {
    key: 'display.collapseThreshold',
    type: 'number',
    default: 30,
    description: 'Line count threshold for collapsing tool output',
    ...numRange(1, 1000),
  },
  {
    key: 'display.theme',
    type: 'string',
    default: 'vaporwave',
    description: 'Color theme name',
  },
  {
    key: 'display.showThinking',
    type: 'boolean',
    default: false,
    description: 'Show reasoning/thinking content in a dimmed block above assistant responses',
  },
  {
    key: 'display.showReasoningSummary',
    type: 'boolean',
    default: false,
    description: 'Show reasoning summary (Mercury-2) in a dimmed block above assistant responses',
  },
  {
    key: 'display.showTokenSpeed',
    type: 'boolean',
    default: false,
    description: 'Show streaming tokens/sec counter during generation',
  },
  {
    key: 'display.showToolPreview',
    type: 'boolean',
    default: false,
    description: 'Show partial tool call preview while streaming',
  },
  {
    key: 'provider.reasoningEffort',
    type: 'enum',
    default: 'medium',
    description: 'Reasoning effort level for models that support it',
    enumValues: ['instant', 'low', 'medium', 'high'],
  },
  {
    key: 'provider.model',
    type: 'string',
    default: 'openrouter:openrouter/free',
    description: 'Default provider-qualified LLM model registry key',
    validate: (v) => {
      if (typeof v !== 'string') return false;
      const separator = v.trim().indexOf(':');
      return separator > 0 && separator < v.trim().length - 1;
    },
  },
  {
    key: 'provider.embeddingProvider',
    type: 'string',
    default: 'hashed-local',
    description: 'Default memory embedding provider',
  },
  {
    key: 'provider.systemPromptFile',
    type: 'string',
    default: '',
    description: 'Path to a file containing the system prompt (empty = none)',
  },
  {
    key: 'provider.optimizerMode',
    type: 'enum',
    default: 'off',
    description:
      'Provider routing optimizer: off (optimizer inactive, default), manual (optimizer active but never auto-routes), auto (selects the best capable provider per request via capability contracts), or pinned (force one model — see provider.optimizerPinnedModel). Runtime /provider commands and pin/unpin still override for the session.',
    enumValues: ['off', 'manual', 'auto', 'pinned'],
  },
  {
    key: 'provider.optimizerPinnedModel',
    type: 'string',
    default: '',
    description:
      'Provider-qualified model id (e.g. anthropic:claude-sonnet-4) pinned by the provider optimizer at startup when provider.optimizerMode is "pinned". Empty leaves the optimizer unpinned (falls back to manual).',
  },
  {
    key: 'behavior.autoApprove',
    type: 'boolean',
    default: false,
    description: 'Auto-approve all tool permission requests (--no-worries-just-vibes)',
  },
  {
    key: 'behavior.autoCompactThreshold',
    type: 'number',
    default: 80,
    description: 'Compact conversation when context usage exceeds this percentage',
    ...numRange(10, 100),
  },
  {
    key: 'behavior.compactionStrategy',
    type: 'enum',
    default: 'structured',
    description: 'Session compaction: off (sessions run uncompacted), structured (in-place summarization with semantic chunking and relevance scoring, default), or distiller (fresh model call producing a continuation brief; falls back to structured below the quality floor and the receipt names any fallback). behavior.autoCompactThreshold sets when compaction triggers.',
    enumValues: ['off', 'structured', 'distiller'],
  },
  {
    key: 'behavior.staleContextWarnings',
    type: 'boolean',
    default: true,
    description: 'Emit proactive context-pressure warnings before compaction is required',
  },
  {
    key: 'behavior.saveHistory',
    type: 'boolean',
    default: true,
    description: 'Persist conversation history to disk',
  },
  {
    key: 'behavior.notifyOnComplete',
    type: 'boolean',
    default: true,
    description: 'Emit terminal bell and desktop notification when a long turn completes',
  },
  {
    key: 'behavior.returnContextMode',
    type: 'enum',
    default: 'off',
    description: 'Resume summary mode: off, local deterministic summary, or helper-assisted summary',
    enumValues: ['off', 'local', 'assisted'],
  },
  {
    key: 'behavior.guidanceMode',
    type: 'enum',
    default: 'minimal',
    description: 'Operational guidance mode: off, minimal, or guided',
    enumValues: ['off', 'minimal', 'guided'],
  },
  {
    key: 'storage.secretPolicy',
    type: 'enum',
    default: 'preferred_secure',
    description: 'Secret persistence policy: plaintext allowed, preferred secure, or require secure',
    enumValues: ['plaintext_allowed', 'preferred_secure', 'require_secure'],
  },
  {
    key: 'storage.artifacts.maxBytes',
    type: 'number',
    default: 512 * 1024 * 1024,
    description: 'Maximum stored artifact size for file, URL, multipart, and raw upload ingest in bytes',
    ...intRange(1 * 1024 * 1024, 10 * 1024 * 1024 * 1024),
  },
  {
    key: 'permissions.mode',
    type: 'enum',
    default: 'prompt',
    description:
      'Session permission mode. prompt (default/"normal"): auto-approve reads, ask for the rest. '
      + 'plan: read-only tools allowed, every mutating/exec tool is refused with a structured plan-mode denial. '
      + 'accept-edits: file write/edit tools auto-approve, exec and other risky classes still ask. '
      + 'allow-all ("auto"): every tool auto-approved. custom: per-tool config actions apply.',
    enumValues: ['prompt', 'allow-all', 'custom', 'plan', 'accept-edits'],
  },
  {
    key: 'permissions.backgroundAgents',
    type: 'enum',
    default: 'inherit',
    description:
      'How background/subagent tool calls consult the permission layer. '
      + 'inherit (default): background tool execution runs through the same session '
      + 'permission mode as the foreground turn loop (allow-all changes nothing; '
      + 'prompt/plan/accept-edits/custom apply their matrices; asks broker through the '
      + 'same blocked-on-user machinery with subagent attribution). '
      + 'allow-all: background agents are exempt — their tool calls auto-approve regardless '
      + 'of the session mode.',
    enumValues: ['inherit', 'allow-all'],
  },
  {
    key: 'permissions.divergenceThreshold',
    type: 'number',
    default: 0.05,
    description:
      'Maximum permission-evaluator divergence rate (0.0–1.0) the permission-divergence-dashboard enforce gate tolerates before blocking a transition from simulation to enforce mode. Default 0.05 = 5%. A per-simulator divergenceThreshold override still wins.',
    ...numRange(0, 1),
  },
  {
    key: 'permissions.maxDivergenceRecords',
    type: 'number',
    default: 500,
    description:
      'Maximum divergence records the permissions simulator retains for the divergence dashboard/trend history. A per-simulator maxDivergenceRecords override still wins.',
    ...intRange(1, 1_000_000),
  },
  {
    key: 'diagnostics.postEdit',
    type: 'enum',
    default: 'on',
    description:
      'Post-edit diagnostics: after a successful file write/edit, append cheap, '
      + 'in-process syntax diagnostics (errors only) for the touched file to the tool '
      + 'result so the model sees a broken edit immediately. on (default): run the '
      + 'tree-sitter syntax provider when a TS/JS project context is detectable (no '
      + 'process spawn, no type checking). off: never append diagnostics.',
    enumValues: ['on', 'off'],
  },
  {
    key: 'permissions.tools.read',
    type: 'enum',
    default: 'allow',
    description: 'Permission for file read operations (read, find, analyze)',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.write',
    type: 'enum',
    default: 'prompt',
    description: 'Permission for file write operations',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.edit',
    type: 'enum',
    default: 'prompt',
    description: 'Permission for file edit/patch operations',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.exec',
    type: 'enum',
    default: 'prompt',
    description: 'Permission for shell command execution',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.find',
    type: 'enum',
    default: 'allow',
    description: 'Permission for file/directory search operations',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.fetch',
    type: 'enum',
    default: 'prompt',
    description: 'Permission for outbound network fetch requests (custom mode only)',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.analyze',
    type: 'enum',
    default: 'allow',
    description: 'Permission for code/project analysis operations',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.inspect',
    type: 'enum',
    default: 'allow',
    description: 'Permission for inspecting runtime state and objects',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.agent',
    type: 'enum',
    default: 'prompt',
    description: 'Permission for spawning subagents or delegating tasks',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.state',
    type: 'enum',
    default: 'allow',
    description: 'Permission for reading runtime/session state',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.workflow',
    type: 'enum',
    default: 'prompt',
    description: 'Permission for executing multi-step workflow automation',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.registry',
    type: 'enum',
    default: 'allow',
    description: 'Permission for querying the tool/skill registry',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.mcp',
    type: 'enum',
    default: 'prompt',
    description: 'Permission for MCP tool calls (external server tools)',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'permissions.tools.delegate',
    type: 'enum',
    default: 'prompt',
    description: 'Permission for unknown or unregistered tools (safe default: prompt)',
    enumValues: ['allow', 'prompt', 'deny'],
  },
  {
    key: 'orchestration.recursionEnabled',
    type: 'boolean',
    default: false,
    description: 'Allow recursive agent orchestration under bounded policy controls',
  },
  {
    key: 'orchestration.maxDepth',
    type: 'number',
    default: 0,
    description: 'Maximum recursive orchestration depth: 0=disabled, higher values allow deeper bounded recursion',
    ...numRange(0, 5),
  },
  {
    key: 'planner.decomposition',
    type: 'enum',
    default: 'agent',
    description: "How /workstream decomposes a goal into work items: 'agent' spawns a read-only planning agent (with automatic fallback to the heuristic path on any failure); 'heuristic' forces the deterministic single-item path and never spawns an agent",
    enumValues: ['agent', 'heuristic'],
  },
  {
    key: 'planner.maxTurns',
    type: 'number',
    default: 6,
    description: 'Maximum turns the planning-decomposition agent may take before it is stopped and the heuristic path is used',
    ...numRange(1, 20),
  },
  {
    key: 'planner.tokenCeiling',
    type: 'number',
    default: 120_000,
    description: 'Total token budget for the planning-decomposition agent; exceeding it stops the agent and falls back to the heuristic path',
    ...numRange(1_000, 2_000_000),
  },
  {
    key: 'planner.wallTimeoutMs',
    type: 'number',
    default: 120_000,
    description: 'Wall-clock timeout (ms) for the planning-decomposition agent; exceeding it cancels the agent and falls back to the heuristic path',
    ...numRange(1_000, 600_000),
  },
  {
    key: 'sandbox.enabled',
    type: 'boolean',
    default: true,
    description:
      'Master switch for the per-command exec sandbox (bubblewrap on Linux): the workspace is writable, the rest of the filesystem is read-only, /tmp is isolated, and network is disabled unless a command is on sandbox.egressAllowlist. Default ON where the host probe passes; honestly reported unavailable when bubblewrap is not present, leaving the exec path unchanged.',
  },
  {
    key: 'sandbox.judgment',
    type: 'enum',
    default: 'annotate',
    description: 'Model-judgment pass on sandbox escalation asks: off (plain asks), annotate (default — a proposed verdict with stated reasons annotates the ask, the human still decides), or auto-approve (additionally auto-approves looks-safe verdicts; explicit opt-in). Never auto-denies and never touches the frozen catastrophic block; every judgment leaves a receipt.',
    enumValues: ['off', 'annotate', 'auto-approve'],
  },
  {
    key: 'sandbox.replIsolation',
    type: 'enum',
    default: 'shared-vm',
    description: 'Preferred isolation mode for evaluation runtimes once virtualization is enabled',
    enumValues: ['shared-vm', 'per-runtime-vm'],
  },
  {
    key: 'sandbox.mcpIsolation',
    type: 'enum',
    default: 'disabled',
    description: 'Preferred isolation mode for MCP servers once virtualization is enabled',
    enumValues: ['disabled', 'shared-vm', 'hybrid', 'per-server-vm'],
  },
  {
    key: 'sandbox.windowsMode',
    type: 'enum',
    default: 'native-basic',
    description: 'Windows host posture: native basic mode or require WSL before enabling virtualized sandboxing',
    enumValues: ['native-basic', 'require-wsl'],
  },
  {
    key: 'sandbox.vmBackend',
    type: 'enum',
    default: 'local',
    description: 'Sandbox backend: local host execution by default, or QEMU for virtualized isolation',
    enumValues: ['local', 'qemu'],
  },
  {
    key: 'sandbox.qemuBinary',
    type: 'string',
    default: 'qemu-system-x86_64',
    description: 'QEMU system binary to use when vmBackend=qemu',
  },
  {
    key: 'sandbox.qemuImagePath',
    type: 'string',
    default: '',
    description: 'Disk image path for QEMU-backed sandbox sessions; when empty, QEMU sessions remain planned-only',
  },
  {
    key: 'sandbox.qemuExecWrapper',
    type: 'string',
    default: '',
    description: 'Host-side wrapper/bridge used to execute guest commands inside a configured QEMU sandbox',
  },
  {
    key: 'sandbox.qemuGuestHost',
    type: 'string',
    default: '',
    description: 'Optional guest host/IP used by the QEMU wrapper for real guest command transport',
  },
  {
    key: 'sandbox.qemuGuestPort',
    type: 'number',
    default: 2222,
    description: 'Optional guest SSH port used by the QEMU wrapper for real guest command transport',
    ...port(),
  },
  {
    key: 'sandbox.qemuGuestUser',
    type: 'string',
    default: 'goodvibes',
    description: 'Optional guest username used by the QEMU wrapper for real guest command transport',
  },
  {
    key: 'sandbox.qemuWorkspacePath',
    type: 'string',
    default: '/workspace',
    description: 'Guest workspace path used by the QEMU wrapper when executing commands inside the guest',
  },
  {
    key: 'sandbox.qemuSessionMode',
    type: 'enum',
    enumValues: ['attach', 'launch-per-command'],
    default: 'attach',
    description: 'Whether the QEMU wrapper attaches to an already running guest or launches a guest per command',
  },
  {
    key: 'sandbox.replJavaScriptCommand',
    type: 'string',
    default: 'bun',
    description: 'Guest command used for JavaScript-family REPL runtimes inside QEMU, including JavaScript, TypeScript, SQL, and GraphQL',
  },
  {
    key: 'ui.voiceEnabled',
    type: 'boolean',
    default: false,
    description: 'Enable the optional local-first voice control surface',
  },
  {
    key: 'ui.systemMessages',
    type: 'enum',
    default: 'panel',
    description: 'Where operational system messages render by default: panel, conversation, or both',
    enumValues: ['panel', 'conversation', 'both'],
  },
  {
    key: 'tts.provider',
    type: 'string',
    default: 'elevenlabs',
    description: 'Default TTS provider used by spoken-output clients when no provider is supplied on the request',
  },
  {
    key: 'tts.voice',
    type: 'string',
    default: '',
    description: 'Default TTS voice id used by spoken-output clients when no voice is supplied on the request',
  },
  {
    key: 'tts.llmProvider',
    type: 'string',
    default: '',
    description: 'Optional LLM provider override for spoken-output turns; empty means use the active chat provider',
  },
  {
    key: 'tts.llmModel',
    type: 'string',
    default: '',
    description: 'Optional LLM model override for spoken-output turns; empty means use the active chat model',
  },
  {
    key: 'tts.speed',
    type: 'number',
    default: 1.0,
    description: 'Playback speed multiplier for TTS synthesis (0.25–4.0); 1.0 is normal speed',
    ...numRange(0.25, 4.0),
  },
  {
    key: 'ui.operationalMessages',
    type: 'enum',
    default: 'panel',
    description: 'Where tool, agent, MCP, plugin, and other operational activity messages render by default: panel, conversation, or both',
    enumValues: ['panel', 'conversation', 'both'],
  },
  {
    key: 'ui.wrfcMessages',
    type: 'enum',
    default: 'both',
    description: 'Where WRFC lifecycle updates render by default: panel, conversation, or both',
    enumValues: ['panel', 'conversation', 'both'],
  },
  {
    key: 'release.channel',
    type: 'enum',
    default: 'stable',
    description: 'Preferred release channel for install/update flows',
    enumValues: ['stable', 'preview'],
  },
];

export const coreTailConfigSettings: ConfigSettingDefinition[] = [
  {
    key: 'daemon.enabled',
    type: 'boolean',
    default: true,
    description:
      'Run the local session daemon (background service that hosts the shared session broker and companion chat). Default on; binds loopback (127.0.0.1) only. Set false to run fully local with no background service.',
  },
  {
    key: 'daemon.embedInProcess',
    type: 'boolean',
    default: false,
    description:
      'NOT RECOMMENDED. When true, and no daemon is already running, host the daemon INSIDE this surface process instead of spawning it as a detached background process. In-process embedding couples the daemon lifetime to this one surface: exiting the surface kills the daemon and every other surface sharing it (single point of failure). Default false — the surface spawns a detached, reboot-independent daemon (install it as a system service via POST /api/service/install on the daemon HTTP API).',
  },
  {
    key: 'danger.httpListener',
    type: 'boolean',
    default: false,
    description: 'Enable HTTP webhook listener for receiving external events',
  },
  {
    key: 'tools.llmEnabled',
    type: 'boolean',
    default: false,
    description: 'Enable dedicated tool LLM for internal operations (off = tools use the main conversation model only when needed)',
  },
  {
    key: 'tools.llmProvider',
    type: 'string',
    default: '',
    description: 'Provider for tool LLM calls (empty = use currently selected provider)',
  },
  {
    key: 'tools.llmModel',
    type: 'string',
    default: '',
    description: 'Model for tool LLM calls (empty = fastest available for the provider)',
  },
  {
    key: 'tools.autoHeal',
    type: 'boolean',
    default: false,
    description: 'Automatically fix syntax errors on precision write/edit operations',
  },
  {
    key: 'tools.defaultTokenBudget',
    type: 'number',
    default: 5000,
    description: 'Default token budget for precision read operations',
    ...numRange(100, 100000),
  },
  {
    key: 'tools.hooksFile',
    type: 'string',
    default: 'hooks.json',
    description: 'Hook configuration file name (relative to the host .goodvibes data directory)',
  },
  {
    key: 'tools.overflowSpillBackend',
    type: 'enum',
    default: 'file',
    description:
      'Where large tool-output overflow content spills: file (on-disk .overflow, default), ledger (execution ledger), or diagnostics. An injected custom backend still takes precedence.',
    enumValues: ['file', 'ledger', 'diagnostics'],
  },
  {
    key: 'wrfc.scoreThreshold',
    type: 'number',
    default: 9.9,
    description: 'Minimum review score to pass WRFC (0-10)',
    ...numRange(0, 10),
  },
  {
    key: 'wrfc.maxFixAttempts',
    type: 'number',
    default: 5,
    description: 'Maximum gate retry depth before aborting WRFC chain',
    ...numRange(1, 20),
  },
  {
    key: 'wrfc.autoCommit',
    type: 'boolean',
    default: true,
    description: 'Auto-commit when WRFC chain passes review and quality gates',
  },
  {
    key: 'wrfc.commitScope',
    type: 'enum',
    default: 'scoped',
    description: 'Scope of files staged on WRFC auto-commit: off (never commit), scoped (only chain-touched files, default), all (legacy full-tree git add -A)',
    enumValues: ['off', 'scoped', 'all'],
  },
  {
    key: 'wrfc.agentHeartbeatTimeoutMs',
    type: 'number',
    default: 0,
    description: 'Watchdog timeout in ms for silent WRFC child agents. 0 = disabled.',
    validate: (v) => typeof v === 'number' && v >= 0,
  },
  {
    key: 'wrfc.transportRetryLimit',
    type: 'number',
    default: 1,
    description: 'How many times a WRFC chain auto-retries a transport/network-classified child-agent failure (respawning the same role) before failing the chain. 0 disables the retry.',
    ...numRange(0, 5),
  },
  {
    key: 'wrfc.transportRetryDelayMs',
    type: 'number',
    default: 5000,
    description: 'Backoff delay in ms before respawning a WRFC child agent after a transport-classified failure.',
    ...numRange(0, 60000),
  },
  {
    key: 'cache.enabled',
    type: 'boolean',
    default: true,
    description: 'Enable prompt caching for eligible providers (Anthropic)',
  },
  {
    key: 'cache.stableTtl',
    type: 'enum',
    default: '1h',
    description: 'Cache TTL for stable content (system prompt + tools): 5m (ephemeral) or 1h (persistent)',
    enumValues: ['5m', '1h'],
  },
  {
    key: 'cache.monitorHitRate',
    type: 'boolean',
    default: true,
    description: 'Monitor cache hit rate and warn when below threshold',
  },
  {
    key: 'cache.hitRateWarningThreshold',
    type: 'number',
    default: 0.3,
    description: 'Warn when cache hit rate falls below this fraction (0.0–1.0)',
    ...numRange(0, 1),
  },
  {
    key: 'helper.enabled',
    type: 'boolean',
    default: false,
    description: 'Enable helper model routing for grunt-work tasks',
  },
  {
    key: 'helper.globalProvider',
    type: 'string',
    default: '',
    description: 'Provider for the global helper model (empty = disabled)',
  },
  {
    key: 'helper.globalModel',
    type: 'string',
    default: '',
    description: 'Model ID for the global helper model (empty = disabled)',
  },
  {
    key: 'behavior.suggestAlternativeOnProviderFail',
    type: 'boolean',
    default: false,
    description: 'Show alternative model suggestion when current provider fails non-transiently',
  },
  {
    key: 'behavior.hitlMode',
    type: 'enum',
    default: 'balanced',
    description: 'Notification verbosity mode applied to the notification router at startup and on change: off (baseline delivery policy, mode changes rejected), quiet (minimal verbosity, long batch windows), balanced (default), or operator (verbose, short batch windows)',
    enumValues: ['off', 'quiet', 'balanced', 'operator'],
  },
];
