version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      production-patches:
        dependency-type: production
        update-types:
          - "version-update:semver-patch"
      development-patches:
        dependency-type: development
        update-types:
          - "version-update:semver-patch"
      production:
        dependency-type: production
      development:
        dependency-type: development
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      github-actions-patches:
        update-types:
          - "version-update:semver-patch"
      github-actions:
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
    labels:
      - "dependencies"
      - "github-actions"
