import type { GatewayMethodDescriptor } from './method-catalog-shared.js';
import {
  BOOLEAN_SCHEMA,
  EMPTY_OBJECT_SCHEMA,
  NUMBER_SCHEMA,
  STRING_SCHEMA,
  actionResultOutputSchema,
  bodyEnvelopeSchema,
  entityOutputSchema,
  listOutputSchema,
  methodDescriptor,
  objectSchema,
  runtimeEventId,
  METHOD_DESCRIPTOR_SCHEMA,
  EVENT_DESCRIPTOR_SCHEMA,
} from './method-catalog-shared.js';
import {
  APPROVAL_ACTION_INPUT_SCHEMA,
  APPROVAL_APPROVE_INPUT_SCHEMA,
  APPROVAL_ACTION_OUTPUT_SCHEMA,
  APPROVAL_SNAPSHOT_SCHEMA,
  CONTROL_AUTH_CURRENT_RESPONSE_SCHEMA,
  CONTROL_AUTH_LOGIN_REQUEST_SCHEMA,
  CONTROL_AUTH_LOGIN_RESPONSE_SCHEMA,
  CONTROL_PLANE_CLIENT_DESCRIPTOR_SCHEMA,
  CONTROL_PLANE_SURFACE_MESSAGE_SCHEMA,
  CONTROL_PLANE_SNAPSHOT_SCHEMA,
  SESSIONS_SEARCH_INPUT_SCHEMA,
  SESSIONS_SEARCH_OUTPUT_SCHEMA,
  OTLP_LOG_DOCUMENT_SCHEMA,
  OTLP_METRIC_DOCUMENT_SCHEMA,
  OTLP_TRACE_DOCUMENT_SCHEMA,
  REVIEW_SNAPSHOT_SCHEMA,
  SESSION_BROKER_SNAPSHOT_SCHEMA,
  SESSION_SNAPSHOT_SCHEMA,
  SHARED_SESSION_CREATE_OUTPUT_SCHEMA,
  SHARED_SESSION_INPUT_RECORD_SCHEMA,
  SHARED_SESSION_MESSAGE_CREATE_OUTPUT_SCHEMA,
  SHARED_SESSION_MESSAGE_ROUTE_OUTPUT_SCHEMA,
  SHARED_SESSION_RECORD_SCHEMA,
  SHARED_SESSION_REGISTER_INPUT_SCHEMA,
  SHARED_SESSION_REGISTER_OUTPUT_SCHEMA,
  SHARED_SESSION_ROUTING_INTENT_SCHEMA,
  SHARED_SESSION_WITH_INPUTS_SCHEMA,
  SHARED_SESSION_WITH_MESSAGES_SCHEMA,
  TASK_ACTION_OUTPUT_SCHEMA,
  TASK_CREATE_INPUT_SCHEMA,
  TASK_CREATE_OUTPUT_SCHEMA,
  TASK_OUTPUT_SCHEMA,
  TASK_SNAPSHOT_SCHEMA,
  TASK_STATUS_OUTPUT_SCHEMA,
  TELEMETRY_FILTER_INPUT_SCHEMA,
  TELEMETRY_METRICS_SNAPSHOT_SCHEMA,
  TELEMETRY_RECORD_LIST_RESPONSE_SCHEMA,
  TELEMETRY_SNAPSHOT_SCHEMA,
  TELEMETRY_SPAN_LIST_RESPONSE_SCHEMA,
  TELEMETRY_STREAM_READY_SCHEMA,
} from './operator-contract-schemas.js';
import { OPERATOR_CONTRACT_SCHEMA } from './operator-contract.js';

export const builtinGatewayControlCoreMethodDescriptors: readonly GatewayMethodDescriptor[] = [
  methodDescriptor({
    id: 'control.auth.login',
    title: 'Login',
    description: 'Authenticate a local control-plane user and create a session token.',
    category: 'control-plane',
    access: 'public',
    transport: ['http'],
    scopes: [],
    http: { method: 'POST', path: '/login' },
    inputSchema: CONTROL_AUTH_LOGIN_REQUEST_SCHEMA,
    outputSchema: CONTROL_AUTH_LOGIN_RESPONSE_SCHEMA,
    invokable: false,
  }),
  methodDescriptor({
    id: 'control.auth.current',
    title: 'Current Auth Context',
    description: 'Return the current control-plane principal, granted scopes, and authentication mode.',
    category: 'control-plane',
    access: 'public',
    scopes: [],
    http: { method: 'GET', path: '/api/control-plane/auth' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: CONTROL_AUTH_CURRENT_RESPONSE_SCHEMA,
  }),
  methodDescriptor({
    id: 'control.status',
    title: 'Daemon Status',
    description: 'Return daemon status and version.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/status' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: objectSchema({
      status: STRING_SCHEMA,
      version: STRING_SCHEMA,
    }, ['status', 'version']),
  }),
  methodDescriptor({
    id: 'control.snapshot',
    title: 'Control-Plane Snapshot',
    description: 'Return the current control-plane gateway snapshot.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane' },
    events: [runtimeEventId('control-plane')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: CONTROL_PLANE_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'control.contract',
    title: 'Operator Contract',
    description: 'Return the operator-facing control-plane contract manifest, including auth, transport, method, and event metadata.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/contract' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: entityOutputSchema('contract', OPERATOR_CONTRACT_SCHEMA),
  }),
  methodDescriptor({
    id: 'control.web',
    title: 'Control-Plane Web Shell',
    description: 'Return the built-in control-plane HTML shell for external clients.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    transport: ['http'],
    http: { method: 'GET', path: '/api/control-plane/web' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: objectSchema({ html: STRING_SCHEMA }, ['html']),
    invokable: false,
    metadata: { responseKind: 'html' },
  }),
  methodDescriptor({
    id: 'control.messages.list',
    title: 'List Control-Plane Messages',
    description: 'Return recent surface messages published through the control plane.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/messages' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('messages', CONTROL_PLANE_SURFACE_MESSAGE_SCHEMA),
  }),
  methodDescriptor({
    id: 'control.clients.list',
    title: 'List Control-Plane Clients',
    description: 'Return authenticated and recently connected control-plane clients.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/clients' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('clients', CONTROL_PLANE_CLIENT_DESCRIPTOR_SCHEMA),
  }),
  methodDescriptor({
    id: 'telemetry.snapshot',
    title: 'Telemetry Snapshot',
    description: 'Return the current telemetry snapshot with aggregates, runtime state, and recent records.',
    category: 'telemetry',
    scopes: ['read:telemetry'],
    http: { method: 'GET', path: '/api/v1/telemetry' },
    inputSchema: TELEMETRY_FILTER_INPUT_SCHEMA,
    outputSchema: TELEMETRY_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'telemetry.events.list',
    title: 'List Telemetry Events',
    description: 'Return a paginated telemetry event feed with cursor-based resume semantics.',
    category: 'telemetry',
    scopes: ['read:telemetry'],
    http: { method: 'GET', path: '/api/v1/telemetry/events' },
    inputSchema: TELEMETRY_FILTER_INPUT_SCHEMA,
    outputSchema: TELEMETRY_RECORD_LIST_RESPONSE_SCHEMA,
  }),
  methodDescriptor({
    id: 'telemetry.errors.list',
    title: 'List Telemetry Errors',
    description: 'Return telemetry records that include normalized error metadata.',
    category: 'telemetry',
    scopes: ['read:telemetry'],
    http: { method: 'GET', path: '/api/v1/telemetry/errors' },
    inputSchema: TELEMETRY_FILTER_INPUT_SCHEMA,
    outputSchema: TELEMETRY_RECORD_LIST_RESPONSE_SCHEMA,
  }),
  methodDescriptor({
    id: 'telemetry.traces.list',
    title: 'List Telemetry Traces',
    description: 'Return synthesized readable spans derived from runtime telemetry.',
    category: 'telemetry',
    scopes: ['read:telemetry'],
    http: { method: 'GET', path: '/api/v1/telemetry/traces' },
    inputSchema: TELEMETRY_FILTER_INPUT_SCHEMA,
    outputSchema: TELEMETRY_SPAN_LIST_RESPONSE_SCHEMA,
  }),
  methodDescriptor({
    id: 'telemetry.metrics.get',
    title: 'Telemetry Metrics',
    description: 'Return telemetry aggregates and runtime metrics without recent record payloads.',
    category: 'telemetry',
    scopes: ['read:telemetry'],
    http: { method: 'GET', path: '/api/v1/telemetry/metrics' },
    inputSchema: TELEMETRY_FILTER_INPUT_SCHEMA,
    outputSchema: TELEMETRY_METRICS_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'telemetry.stream',
    title: 'Telemetry Event Stream',
    description: 'Open the telemetry SSE stream and emit a ready event with resume metadata.',
    category: 'telemetry',
    scopes: ['read:telemetry'],
    transport: ['http'],
    http: { method: 'GET', path: '/api/v1/telemetry/stream' },
    inputSchema: TELEMETRY_FILTER_INPUT_SCHEMA,
    outputSchema: TELEMETRY_STREAM_READY_SCHEMA,
    invokable: false,
    metadata: { responseKind: 'sse', stream: true, wireEvent: 'telemetry' },
  }),
  methodDescriptor({
    id: 'telemetry.otlp.traces',
    title: 'OTLP Trace Export',
    description: 'Return telemetry traces encoded as OTLP-compatible JSON.',
    category: 'telemetry',
    scopes: ['read:telemetry'],
    http: { method: 'GET', path: '/api/v1/telemetry/otlp/v1/traces' },
    inputSchema: TELEMETRY_FILTER_INPUT_SCHEMA,
    outputSchema: OTLP_TRACE_DOCUMENT_SCHEMA,
  }),
  methodDescriptor({
    id: 'telemetry.otlp.logs',
    title: 'OTLP Log Export',
    description: 'Return telemetry events encoded as OTLP-compatible log documents.',
    category: 'telemetry',
    scopes: ['read:telemetry'],
    http: { method: 'GET', path: '/api/v1/telemetry/otlp/v1/logs' },
    inputSchema: TELEMETRY_FILTER_INPUT_SCHEMA,
    outputSchema: OTLP_LOG_DOCUMENT_SCHEMA,
  }),
  methodDescriptor({
    id: 'telemetry.otlp.metrics',
    title: 'OTLP Metric Export',
    description: 'Return telemetry metrics encoded as OTLP-compatible metric documents.',
    category: 'telemetry',
    scopes: ['read:telemetry'],
    http: { method: 'GET', path: '/api/v1/telemetry/otlp/v1/metrics' },
    inputSchema: TELEMETRY_FILTER_INPUT_SCHEMA,
    outputSchema: OTLP_METRIC_DOCUMENT_SCHEMA,
  }),
  methodDescriptor({
    id: 'control.methods.list',
    title: 'List Gateway Methods',
    description: 'Return the gateway method catalog.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/methods' },
    inputSchema: objectSchema({
      category: STRING_SCHEMA,
      source: STRING_SCHEMA,
    }),
    outputSchema: listOutputSchema('methods', METHOD_DESCRIPTOR_SCHEMA),
  }),
  methodDescriptor({
    id: 'control.methods.get',
    title: 'Get Gateway Method',
    description: 'Return a single gateway method descriptor.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/methods/{methodId}' },
    inputSchema: objectSchema({
      methodId: STRING_SCHEMA,
    }, ['methodId']),
    outputSchema: entityOutputSchema('method', METHOD_DESCRIPTOR_SCHEMA),
  }),
  methodDescriptor({
    id: 'control.events.catalog',
    title: 'List Gateway Events',
    description: 'Return the event catalog for SSE and WebSocket control-plane subscriptions.',
    category: 'control-plane',
    scopes: ['read:control-plane', 'read:events'],
    http: { method: 'GET', path: '/api/control-plane/events/catalog' },
    inputSchema: objectSchema({
      category: STRING_SCHEMA,
      domain: STRING_SCHEMA,
    }),
    outputSchema: listOutputSchema('events', EVENT_DESCRIPTOR_SCHEMA),
  }),
  methodDescriptor({
    id: 'control.events.stream',
    title: 'Open Control-Plane Event Stream',
    description: 'Open the SSE control-plane event stream.',
    category: 'control-plane',
    scopes: ['read:events'],
    transport: ['http'],
    http: { method: 'GET', path: '/api/control-plane/events' },
    inputSchema: objectSchema({
      domains: STRING_SCHEMA,
    }),
    outputSchema: objectSchema({
      contentType: STRING_SCHEMA,
      mode: STRING_SCHEMA,
    }, ['contentType', 'mode']),
    invokable: false,
    metadata: { responseKind: 'sse', stream: true },
  }),
  methodDescriptor({
    id: 'review.snapshot',
    title: 'Review Snapshot',
    description: 'Return the integration review snapshot used by external helpers.',
    category: 'review',
    scopes: ['read:automation'],
    http: { method: 'GET', path: '/api/review' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: REVIEW_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.integration.snapshot',
    title: 'Session Integration Snapshot',
    description: 'Return the session integration snapshot.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/session' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: SESSION_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.list',
    title: 'List Shared Sessions',
    description: 'Return shared-session integration state.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/sessions' },
    events: [runtimeEventId('session')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: SESSION_BROKER_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.create',
    title: 'Create Shared Session',
    description: 'Create a shared session for a surface, route, or web client.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions' },
    events: ['control.session_update'],
    inputSchema: bodyEnvelopeSchema({
      title: STRING_SCHEMA,
      surfaceKind: STRING_SCHEMA,
      surfaceId: STRING_SCHEMA,
    }),
    outputSchema: SHARED_SESSION_CREATE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.register',
    title: 'Register Shared Session',
    description: 'Idempotently register (or heartbeat) a session keyed on a caller-supplied id, carrying its kind, project, and participant identity. Re-calling with the same id advances the participant lastSeenAt (heartbeat). Registering against a CLOSED session does NOT silently reopen it — the heartbeat is recorded and the still-closed record is returned with reopened=false and conflict={status:closed}; pass reopen=true to reopen. A titled session is never renamed by the heartbeat. An unknown kind is rejected (400), not coerced. Prefer this over sessions.create for external runtimes that own their session id.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/register' },
    events: ['control.session_update'],
    inputSchema: SHARED_SESSION_REGISTER_INPUT_SCHEMA,
    outputSchema: SHARED_SESSION_REGISTER_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.get',
    title: 'Get Shared Session',
    description: 'Return metadata for a shared session.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/sessions/{sessionId}' },
    inputSchema: objectSchema({ sessionId: STRING_SCHEMA }, ['sessionId']),
    outputSchema: SHARED_SESSION_WITH_MESSAGES_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.close',
    title: 'Close Shared Session',
    description: 'Mark a shared session as closed.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/close' },
    events: ['control.session_update'],
    inputSchema: objectSchema({ sessionId: STRING_SCHEMA }, ['sessionId']),
    outputSchema: actionResultOutputSchema('session', SHARED_SESSION_RECORD_SCHEMA),
  }),
  methodDescriptor({
    id: 'sessions.reopen',
    title: 'Reopen Shared Session',
    description: 'Reopen a previously closed shared session.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/reopen' },
    events: ['control.session_update'],
    inputSchema: objectSchema({ sessionId: STRING_SCHEMA }, ['sessionId']),
    outputSchema: actionResultOutputSchema('session', SHARED_SESSION_RECORD_SCHEMA),
  }),
  methodDescriptor({
    id: 'sessions.detach',
    title: 'Detach Shared Session Participant',
    description: 'Remove a surface\'s participant and its route binding from a session so that surface stops receiving updates, WITHOUT closing or killing the session (detach != close != kill). Every participant carrying the given surfaceId is removed and any route binding they alone held is unbound; the session and all other participants keep running. Idempotent: detaching an already-detached surface, or detaching from a closed session, is a no-op success. An unknown session is a 404.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/detach' },
    events: ['control.session_update'],
    inputSchema: objectSchema({
      sessionId: STRING_SCHEMA,
      surfaceId: STRING_SCHEMA,
    }, ['sessionId', 'surfaceId']),
    outputSchema: actionResultOutputSchema('session', SHARED_SESSION_RECORD_SCHEMA),
  }),
  methodDescriptor({
    id: 'sessions.delete',
    title: 'Delete Shared Session',
    description: 'Permanently remove a shared session record and its queued inputs/messages from the home-scoped store. A distinct, explicit hard-delete verb — NEVER triggered by close; closed sessions stay listable (includeClosed) and deletionRetentionMs semantics for non-deleted records are untouched. Requires the session to already be closed: deleting a still-active session is rejected with 409 SESSION_ACTIVE (close it, then delete). An unknown or already-deleted id is a 404 SESSION_NOT_FOUND, never a 200-noop. Emits control.session_update (session-deleted) so subscribers drop the row live.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'DELETE', path: '/api/sessions/{sessionId}' },
    events: ['control.session_update'],
    inputSchema: objectSchema({ sessionId: STRING_SCHEMA }, ['sessionId']),
    outputSchema: objectSchema({
      sessionId: STRING_SCHEMA,
      deleted: BOOLEAN_SCHEMA,
    }, ['sessionId', 'deleted']),
  }),
  methodDescriptor({
    id: 'sessions.messages.list',
    title: 'List Shared Session Messages',
    description: 'Return message history for a shared session.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/sessions/{sessionId}/messages' },
    inputSchema: objectSchema({
      sessionId: STRING_SCHEMA,
      limit: NUMBER_SCHEMA,
      before: STRING_SCHEMA,
    }, ['sessionId']),
    outputSchema: SHARED_SESSION_WITH_MESSAGES_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.messages.create',
    title: 'Post Shared Session Message',
    description: 'Append a user message to a shared session. Omitted `kind` defaults to `message` conversation routing; send `kind: "task"` to request agent/WRFC task continuation.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/messages' },
    events: ['control.session_update'],
    inputSchema: bodyEnvelopeSchema({
      body: STRING_SCHEMA,
      surfaceKind: STRING_SCHEMA,
      surfaceId: STRING_SCHEMA,
      kind: STRING_SCHEMA,
      routing: SHARED_SESSION_ROUTING_INTENT_SCHEMA,
    }, ['body']),
    outputSchema: SHARED_SESSION_MESSAGE_ROUTE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.inputs.list',
    title: 'List Shared Session Inputs',
    description: 'Return explicit session inputs, including queued follow-ups and delivered steering requests. A live surface collects work by filtering `state` (e.g. queued) and paging past a `since` createdAt cursor (exclusive), draining only inputs it has not yet collected.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/sessions/{sessionId}/inputs' },
    inputSchema: objectSchema({
      sessionId: STRING_SCHEMA,
      limit: NUMBER_SCHEMA,
      state: STRING_SCHEMA,
      since: NUMBER_SCHEMA,
    }, ['sessionId']),
    outputSchema: SHARED_SESSION_WITH_INPUTS_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.steer',
    title: 'Steer Shared Session',
    description: 'Deliver a live steering message to the active agent for a shared session, optionally falling back to spawn when explicitly allowed.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/steer' },
    events: ['control.session_update'],
    inputSchema: bodyEnvelopeSchema({
      body: STRING_SCHEMA,
      surfaceKind: STRING_SCHEMA,
      surfaceId: STRING_SCHEMA,
      routing: SHARED_SESSION_ROUTING_INTENT_SCHEMA,
      allowSpawnFallback: BOOLEAN_SCHEMA,
    }, ['body']),
    outputSchema: SHARED_SESSION_MESSAGE_CREATE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.followUp',
    title: 'Queue Shared Session Follow-Up',
    description: 'Queue a deferred follow-up for a shared session so it runs after the current agent completes, or spawn immediately when the session is idle.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/follow-up' },
    events: ['control.session_update'],
    inputSchema: bodyEnvelopeSchema({
      body: STRING_SCHEMA,
      surfaceKind: STRING_SCHEMA,
      surfaceId: STRING_SCHEMA,
      routing: SHARED_SESSION_ROUTING_INTENT_SCHEMA,
    }, ['body']),
    outputSchema: SHARED_SESSION_MESSAGE_CREATE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.inputs.cancel',
    title: 'Cancel Shared Session Input',
    description: 'Cancel a queued shared-session input before it is delivered or spawned.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/inputs/{inputId}/cancel' },
    events: ['control.session_update'],
    inputSchema: objectSchema({
      sessionId: STRING_SCHEMA,
      inputId: STRING_SCHEMA,
    }, ['sessionId', 'inputId']),
    outputSchema: entityOutputSchema('input', SHARED_SESSION_INPUT_RECORD_SCHEMA),
  }),
  methodDescriptor({
    id: 'sessions.inputs.deliver',
    title: 'Mark Shared Session Input Delivered',
    description: 'A live registered surface reports that it collected a queued input (moves it to `delivered`) or finished acting on it (`consumed:true` moves it to `completed`). This is how a surface-managed session — where steer/follow-up inputs queue for the surface rather than spawn a daemon executor — closes the input lifecycle honestly. Only queued/delivered inputs advance; others are returned unchanged.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/inputs/{inputId}/deliver' },
    events: ['control.session_update'],
    inputSchema: objectSchema({
      sessionId: STRING_SCHEMA,
      inputId: STRING_SCHEMA,
      consumed: BOOLEAN_SCHEMA,
    }, ['sessionId', 'inputId']),
    outputSchema: entityOutputSchema('input', SHARED_SESSION_INPUT_RECORD_SCHEMA),
  }),
  // ── sessions.search (see CHANGELOG 1.0.0) ────────────────────────────────
  // Paginated/filtered query over the home-scoped session store, extending
  // the session-spine list-filter shape (project/kind/includeClosed) with free-text
  // `query`, `surfaceKind`, `status`, and opaque cursor pagination. Handler:
  // routes/session-search.ts (registered directly on the catalog with no
  // `http` REST binding — see the transport note below).
  //
  // TRANSPORT NOTE (applies to sessions.search + the whole fleet.*/
  // checkpoints.* block below): `transport: ['ws']` with no `http` binding is
  // the transport-parity gate's (test/transport-parity.test.ts) own
  // sanctioned category for a catalog method dispatchable ONLY via the
  // generic invoke-by-id mechanism (`gatewayMethods.hasHandler`/`invoke`,
  // daemon/control-plane.ts `invokeGatewayMethodCall`) rather than a
  // dedicated REST path — reachable today over HTTP via
  // `POST /api/control-plane/methods/{methodId}/invoke` AND over WebSocket
  // via a `{type:'call', methodId}` frame (both converge on the same
  // invokeGatewayMethodCall). A typed client wrapper (operator-sdk
  // client-core.ts's invokeContractRoute, which dispatches by literal
  // http.method/http.path) is NOT wired for these verbs by this brief —
  // that is curated, consumer-side work for whichever later stage first
  // needs a typed wrapper (W1/W2/T2), not a requirement of landing the SDK
  // contract itself.
  methodDescriptor({
    id: 'sessions.search',
    title: 'Search Shared Sessions',
    description: 'Paginated, filtered query over shared sessions: free-text query (matches id/title), project, kind, surfaceKind, and status. Closed sessions are EXCLUDED by default — pass includeClosed:true to include them, and a returned closed session always carries an honest status:"closed" (never hidden, never relabeled). Cursor pagination returns disjoint pages that union to the full matching set.',
    category: 'sessions',
    scopes: ['read:sessions'],
    transport: ['ws'],
    inputSchema: SESSIONS_SEARCH_INPUT_SCHEMA,
    outputSchema: SESSIONS_SEARCH_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.list',
    title: 'List Runtime Tasks',
    description: 'Return the integration snapshot for runtime tasks.',
    category: 'tasks',
    scopes: ['read:tasks'],
    http: { method: 'GET', path: '/api/tasks' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: TASK_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.create',
    title: 'Create Task',
    description: 'Submit a task to the daemon or a shared session.',
    category: 'tasks',
    scopes: ['write:tasks'],
    http: { method: 'POST', path: '/task' },
    events: [runtimeEventId('tasks')],
    inputSchema: TASK_CREATE_INPUT_SCHEMA,
    outputSchema: TASK_CREATE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.get',
    title: 'Get Runtime Task',
    description: 'Return a single runtime task record.',
    category: 'tasks',
    scopes: ['read:tasks'],
    http: { method: 'GET', path: '/api/tasks/{taskId}' },
    inputSchema: objectSchema({ taskId: STRING_SCHEMA }, ['taskId']),
    outputSchema: TASK_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.cancel',
    title: 'Cancel Runtime Task',
    description: 'Cancel an in-flight runtime task.',
    category: 'tasks',
    scopes: ['write:tasks'],
    http: { method: 'POST', path: '/api/tasks/{taskId}/cancel' },
    inputSchema: objectSchema({ taskId: STRING_SCHEMA }, ['taskId']),
    outputSchema: TASK_ACTION_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.retry',
    title: 'Retry Runtime Task',
    description: 'Retry a runtime task through the task action endpoint.',
    category: 'tasks',
    scopes: ['write:tasks'],
    http: { method: 'POST', path: '/api/tasks/{taskId}/retry' },
    inputSchema: objectSchema({ taskId: STRING_SCHEMA }, ['taskId']),
    outputSchema: TASK_ACTION_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.status',
    title: 'Get Task Status',
    description: 'Return lightweight runtime task status by agent id.',
    category: 'tasks',
    scopes: ['read:tasks'],
    http: { method: 'GET', path: '/task/{agentId}' },
    inputSchema: objectSchema({ agentId: STRING_SCHEMA }, ['agentId']),
    outputSchema: TASK_STATUS_OUTPUT_SCHEMA,
  }),
  // fleet.* + checkpoints.* descriptors moved to method-catalog-fleet.ts
  // (see CHANGELOG 1.0.0) — this file was already at the 800-line cap; see that file's
  // header comment for the full design rationale, merged in by
  // method-catalog-control.ts alongside method-catalog-control-automation.ts.
  methodDescriptor({
    id: 'approvals.list',
    title: 'List Approvals',
    description: 'Return pending and historical approval records.',
    category: 'approvals',
    scopes: ['read:approvals'],
    http: { method: 'GET', path: '/api/approvals' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: APPROVAL_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.claim',
    title: 'Claim Approval',
    description: 'Claim a pending approval for operator handling.',
    category: 'approvals',
    scopes: ['write:approvals'],
    http: { method: 'POST', path: '/api/approvals/{approvalId}/claim' },
    inputSchema: objectSchema({ approvalId: STRING_SCHEMA }, ['approvalId']),
    outputSchema: APPROVAL_ACTION_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.approve',
    title: 'Approve Approval',
    description: 'Approve a pending approval. Optionally pass selectedHunks (edit-tool approvals only): the daemon filters the approval\'s own edit list to those hunk indices server-side, so every surface produces identical modified-edit args. Omitting selectedHunks approves the whole request (back-compat). An out-of-range index or a non-edit approval is rejected with a 400.',
    category: 'approvals',
    scopes: ['write:approvals'],
    http: { method: 'POST', path: '/api/approvals/{approvalId}/approve' },
    inputSchema: APPROVAL_APPROVE_INPUT_SCHEMA,
    outputSchema: APPROVAL_ACTION_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.deny',
    title: 'Deny Approval',
    description: 'Deny a pending approval.',
    category: 'approvals',
    scopes: ['write:approvals'],
    http: { method: 'POST', path: '/api/approvals/{approvalId}/deny' },
    inputSchema: APPROVAL_ACTION_INPUT_SCHEMA,
    outputSchema: APPROVAL_ACTION_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.cancel',
    title: 'Cancel Approval',
    description: 'Cancel a pending approval.',
    category: 'approvals',
    scopes: ['write:approvals'],
    http: { method: 'POST', path: '/api/approvals/{approvalId}/cancel' },
    inputSchema: APPROVAL_ACTION_INPUT_SCHEMA,
    outputSchema: APPROVAL_ACTION_OUTPUT_SCHEMA,
  }),
];
