import type { GatewayMethodDescriptor } from './method-catalog-shared.js';
import {
  EMPTY_OBJECT_SCHEMA,
  BOOLEAN_SCHEMA,
  STRING_SCHEMA,
  NUMBER_SCHEMA,
  objectSchema,
  listOutputSchema,
  entityOutputSchema,
  bodyEnvelopeSchema,
  methodDescriptor,
  runtimeEventId,
  arraySchema,
} from './method-catalog-shared.js';
import { enumSchema, nullableSchema } from './operator-contract-schemas-shared.js';
import {
  CONTINUITY_SNAPSHOT_SCHEMA,
  DISTRIBUTED_NODE_HOST_CONTRACT_SCHEMA,
  HEALTH_SNAPSHOT_SCHEMA,
  INTELLIGENCE_SNAPSHOT_SCHEMA,
  MEMORY_DOCTOR_REPORT_SCHEMA,
  MEMORY_VECTOR_STATS_SCHEMA,
  PROVIDER_ACCOUNT_SNAPSHOT_SCHEMA,
  PROVIDER_RUNTIME_SNAPSHOT_SCHEMA,
  PROVIDER_USAGE_SNAPSHOT_SCHEMA,
  REMOTE_PAIR_APPROVAL_OUTPUT_SCHEMA,
  REMOTE_PAIR_REQUEST_OUTPUT_SCHEMA,
  REMOTE_PAIR_REQUESTS_OUTPUT_SCHEMA,
  REMOTE_PEERS_OUTPUT_SCHEMA,
  REMOTE_PAIR_REQUEST_ACTION_INPUT_SCHEMA,
  REMOTE_PEER_DISCONNECT_INPUT_SCHEMA,
  REMOTE_PEER_INVOKE_INPUT_SCHEMA,
  REMOTE_PEER_INVOKE_OUTPUT_SCHEMA,
  REMOTE_PEER_OUTPUT_SCHEMA,
  REMOTE_PEER_TOKEN_REVOKE_INPUT_SCHEMA,
  REMOTE_PEER_TOKEN_ROTATE_INPUT_SCHEMA,
  REMOTE_PEER_TOKEN_ROTATE_OUTPUT_SCHEMA,
  REMOTE_SNAPSHOT_SCHEMA,
  REMOTE_WORK_LIST_OUTPUT_SCHEMA,
  REMOTE_WORK_CANCEL_INPUT_SCHEMA,
  REMOTE_WORK_OUTPUT_SCHEMA,
  SECURITY_SETTINGS_REPORT_SCHEMA,
  SETTINGS_SNAPSHOT_SCHEMA,
  WORKTREE_SNAPSHOT_SCHEMA,
} from './operator-contract-schemas.js';

const MCP_SCOPE_SCHEMA = enumSchema(['project', 'global']);
const MCP_SERVER_CONFIG_SCHEMA = objectSchema({
  name: STRING_SCHEMA,
  command: STRING_SCHEMA,
  args: arraySchema(STRING_SCHEMA),
  env: objectSchema({}, [], { additionalProperties: true }),
  envKeys: arraySchema(STRING_SCHEMA),
  role: nullableSchema(STRING_SCHEMA),
  trustMode: nullableSchema(STRING_SCHEMA),
  allowedPaths: arraySchema(STRING_SCHEMA),
  allowedHosts: arraySchema(STRING_SCHEMA),
}, ['name', 'command']);
const MCP_CONFIG_SOURCE_SCHEMA = objectSchema({
  scope: STRING_SCHEMA,
  kind: STRING_SCHEMA,
  path: STRING_SCHEMA,
  writable: BOOLEAN_SCHEMA,
}, ['scope', 'kind', 'path', 'writable']);
const MCP_CONFIG_SERVER_SCHEMA = objectSchema({
  name: STRING_SCHEMA,
  command: STRING_SCHEMA,
  args: arraySchema(STRING_SCHEMA),
  envKeys: arraySchema(STRING_SCHEMA),
  role: nullableSchema(STRING_SCHEMA),
  trustMode: nullableSchema(STRING_SCHEMA),
  allowedPaths: arraySchema(STRING_SCHEMA),
  allowedHosts: arraySchema(STRING_SCHEMA),
  source: MCP_CONFIG_SOURCE_SCHEMA,
}, ['name', 'command', 'args', 'envKeys', 'role', 'trustMode', 'allowedPaths', 'allowedHosts', 'source']);
const MCP_RELOAD_SERVER_SCHEMA = objectSchema({
  name: STRING_SCHEMA,
  action: enumSchema(['added', 'changed', 'removed', 'unchanged']),
  connected: BOOLEAN_SCHEMA,
}, ['name', 'action', 'connected']);
const MCP_RELOAD_RESULT_SCHEMA = objectSchema({
  added: NUMBER_SCHEMA,
  changed: NUMBER_SCHEMA,
  removed: NUMBER_SCHEMA,
  unchanged: NUMBER_SCHEMA,
  servers: arraySchema(MCP_RELOAD_SERVER_SCHEMA),
}, ['added', 'changed', 'removed', 'unchanged', 'servers']);
const MCP_CONFIG_RESPONSE_SCHEMA = objectSchema({
  locations: arraySchema(MCP_CONFIG_SOURCE_SCHEMA),
  servers: arraySchema(MCP_CONFIG_SERVER_SCHEMA),
}, ['locations', 'servers']);
const MCP_CONFIG_MUTATION_RESPONSE_SCHEMA = objectSchema({
  scope: MCP_SCOPE_SCHEMA,
  path: STRING_SCHEMA,
  removed: BOOLEAN_SCHEMA,
  reload: MCP_RELOAD_RESULT_SCHEMA,
  config: MCP_CONFIG_RESPONSE_SCHEMA,
}, ['scope', 'path', 'reload', 'config']);
const MCP_SERVER_STATUS_SCHEMA = objectSchema({
  name: STRING_SCHEMA,
  connected: BOOLEAN_SCHEMA,
}, ['name', 'connected']);
const MCP_SERVERS_RESPONSE_SCHEMA = objectSchema({
  servers: arraySchema(MCP_SERVER_STATUS_SCHEMA),
  security: arraySchema(objectSchema({}, [], { additionalProperties: true })),
  sandboxBindings: arraySchema(objectSchema({}, [], { additionalProperties: true })),
}, ['servers', 'security', 'sandboxBindings']);
const MCP_TOOL_SCHEMA = objectSchema({
  qualifiedName: STRING_SCHEMA,
  serverName: STRING_SCHEMA,
  toolName: STRING_SCHEMA,
  description: STRING_SCHEMA,
}, ['qualifiedName', 'serverName', 'toolName', 'description']);
const MCP_TOOLS_RESPONSE_SCHEMA = objectSchema({
  tools: arraySchema(MCP_TOOL_SCHEMA),
}, ['tools']);

export const builtinGatewayRuntimeMethodDescriptors: readonly GatewayMethodDescriptor[] = [
  methodDescriptor({
    id: 'mcp.config.get',
    title: 'MCP Effective Config',
    description: 'Return effective MCP config from global, external, and project sources. Environment values are redacted to envKeys.',
    category: 'mcp',
    scopes: ['read:mcp'],
    http: { method: 'GET', path: '/api/mcp/config' },
    events: [runtimeEventId('mcp')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: MCP_CONFIG_RESPONSE_SCHEMA,
  }),
  methodDescriptor({
    id: 'mcp.servers.list',
    title: 'MCP Servers List',
    description: 'Return configured MCP servers, runtime security posture, and sandbox bindings.',
    category: 'mcp',
    scopes: ['read:mcp'],
    http: { method: 'GET', path: '/api/mcp/servers' },
    events: [runtimeEventId('mcp')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: MCP_SERVERS_RESPONSE_SCHEMA,
  }),
  methodDescriptor({
    id: 'mcp.tools.list',
    title: 'MCP Tools List',
    description: 'Return currently connected MCP tools.',
    category: 'mcp',
    scopes: ['read:mcp'],
    http: { method: 'GET', path: '/api/mcp/tools' },
    events: [runtimeEventId('mcp')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: MCP_TOOLS_RESPONSE_SCHEMA,
  }),
  methodDescriptor({
    id: 'mcp.config.reload',
    title: 'Reload MCP Config',
    description: 'Reload effective MCP config and reconnect added, removed, or changed servers without daemon restart.',
    category: 'mcp',
    scopes: ['write:mcp'],
    access: 'admin',
    http: { method: 'POST', path: '/api/mcp/reload' },
    events: [runtimeEventId('mcp')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: objectSchema({
      reload: MCP_RELOAD_RESULT_SCHEMA,
      config: MCP_CONFIG_RESPONSE_SCHEMA,
    }, ['reload', 'config']),
  }),
  methodDescriptor({
    id: 'mcp.servers.upsert',
    title: 'Upsert MCP Server',
    description: 'Persist a project/global MCP server config and reconnect the changed runtime server without daemon restart.',
    category: 'mcp',
    scopes: ['write:mcp'],
    access: 'admin',
    http: { method: 'POST', path: '/api/mcp/config/servers' },
    events: [runtimeEventId('mcp')],
    inputSchema: bodyEnvelopeSchema({
      scope: MCP_SCOPE_SCHEMA,
      server: MCP_SERVER_CONFIG_SCHEMA,
    }, ['server']),
    outputSchema: MCP_CONFIG_MUTATION_RESPONSE_SCHEMA,
  }),
  methodDescriptor({
    id: 'mcp.servers.remove',
    title: 'Remove MCP Server',
    description: 'Remove a project/global MCP server config and disconnect it without daemon restart.',
    category: 'mcp',
    scopes: ['write:mcp'],
    access: 'admin',
    http: { method: 'DELETE', path: '/api/mcp/config/servers/{serverName}' },
    events: [runtimeEventId('mcp')],
    inputSchema: objectSchema({
      serverName: STRING_SCHEMA,
      scope: MCP_SCOPE_SCHEMA,
    }, ['serverName']),
    outputSchema: MCP_CONFIG_MUTATION_RESPONSE_SCHEMA,
  }),
  methodDescriptor({
    id: 'remote.snapshot',
    title: 'Remote Runtime Snapshot',
    description: 'Return distributed node/device runtime state.',
    category: 'remote',
    scopes: ['read:remote'],
    http: { method: 'GET', path: '/api/remote' },
    events: [runtimeEventId('control-plane')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: REMOTE_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'remote.pair.requests.list',
    title: 'List Remote Pair Requests',
    description: 'Return pending remote pair requests.',
    category: 'remote',
    scopes: ['read:remote'],
    http: { method: 'GET', path: '/api/remote/pair/requests' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: REMOTE_PAIR_REQUESTS_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'remote.pair.requests.approve',
    title: 'Approve Remote Pair Request',
    description: 'Approve a pending remote pair request.',
    category: 'remote',
    scopes: ['write:remote'],
    access: 'admin',
    http: { method: 'POST', path: '/api/remote/pair/requests/{requestId}/approve' },
    inputSchema: REMOTE_PAIR_REQUEST_ACTION_INPUT_SCHEMA,
    outputSchema: REMOTE_PAIR_APPROVAL_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'remote.pair.requests.reject',
    title: 'Reject Remote Pair Request',
    description: 'Reject a pending remote pair request.',
    category: 'remote',
    scopes: ['write:remote'],
    access: 'admin',
    http: { method: 'POST', path: '/api/remote/pair/requests/{requestId}/reject' },
    inputSchema: REMOTE_PAIR_REQUEST_ACTION_INPUT_SCHEMA,
    outputSchema: REMOTE_PAIR_REQUEST_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'remote.peers.list',
    title: 'List Remote Peers',
    description: 'Return known remote peers.',
    category: 'remote',
    scopes: ['read:remote'],
    http: { method: 'GET', path: '/api/remote/peers' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: REMOTE_PEERS_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'remote.peers.token.rotate',
    title: 'Rotate Remote Peer Token',
    description: 'Rotate the active token for a remote peer.',
    category: 'remote',
    scopes: ['write:remote'],
    access: 'admin',
    http: { method: 'POST', path: '/api/remote/peers/{peerId}/token/rotate' },
    inputSchema: REMOTE_PEER_TOKEN_ROTATE_INPUT_SCHEMA,
    outputSchema: REMOTE_PEER_TOKEN_ROTATE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'remote.peers.token.revoke',
    title: 'Revoke Remote Peer Token',
    description: 'Revoke the active token for a remote peer.',
    category: 'remote',
    scopes: ['write:remote'],
    access: 'admin',
    http: { method: 'POST', path: '/api/remote/peers/{peerId}/token/revoke' },
    inputSchema: REMOTE_PEER_TOKEN_REVOKE_INPUT_SCHEMA,
    outputSchema: REMOTE_PEER_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'remote.peers.disconnect',
    title: 'Disconnect Remote Peer',
    description: 'Disconnect a remote peer.',
    category: 'remote',
    scopes: ['write:remote'],
    access: 'admin',
    http: { method: 'POST', path: '/api/remote/peers/{peerId}/disconnect' },
    inputSchema: REMOTE_PEER_DISCONNECT_INPUT_SCHEMA,
    outputSchema: REMOTE_PEER_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'remote.peers.invoke',
    title: 'Invoke Remote Peer',
    description: 'Invoke a method on a connected remote peer.',
    category: 'remote',
    scopes: ['write:remote'],
    access: 'admin',
    http: { method: 'POST', path: '/api/remote/peers/{peerId}/invoke' },
    inputSchema: REMOTE_PEER_INVOKE_INPUT_SCHEMA,
    outputSchema: REMOTE_PEER_INVOKE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'remote.work.list',
    title: 'List Remote Work',
    description: 'Return queued and leased remote work items.',
    category: 'remote',
    scopes: ['read:remote'],
    http: { method: 'GET', path: '/api/remote/work' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: REMOTE_WORK_LIST_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'remote.work.cancel',
    title: 'Cancel Remote Work',
    description: 'Cancel a remote work item.',
    category: 'remote',
    scopes: ['write:remote'],
    access: 'admin',
    http: { method: 'POST', path: '/api/remote/work/{workId}/cancel' },
    inputSchema: REMOTE_WORK_CANCEL_INPUT_SCHEMA,
    outputSchema: REMOTE_WORK_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'remote.node_host.contract',
    title: 'Node Host Contract',
    description: 'Return the distributed node/device host API contract.',
    category: 'remote',
    scopes: ['read:remote'],
    http: { method: 'GET', path: '/api/remote/node-host/contract' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: entityOutputSchema('contract', DISTRIBUTED_NODE_HOST_CONTRACT_SCHEMA),
  }),
  methodDescriptor({
    id: 'health.snapshot',
    title: 'Health Snapshot',
    description: 'Return the health integration snapshot.',
    category: 'health',
    scopes: ['read:health'],
    http: { method: 'GET', path: '/api/health' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: HEALTH_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'accounts.snapshot',
    title: 'Accounts Snapshot',
    description: 'Return provider account posture.',
    category: 'accounts',
    scopes: ['read:accounts'],
    http: { method: 'GET', path: '/api/accounts' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: PROVIDER_ACCOUNT_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'providers.list',
    title: 'Providers List',
    description: 'Return runtime provider metadata, policy hooks, and priced model summaries.',
    category: 'providers',
    scopes: ['read:providers'],
    http: { method: 'GET', path: '/api/providers' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('providers', PROVIDER_RUNTIME_SNAPSHOT_SCHEMA),
  }),
  methodDescriptor({
    id: 'providers.get',
    title: 'Provider Snapshot',
    description: 'Return runtime metadata for a single provider.',
    category: 'providers',
    scopes: ['read:providers'],
    http: { method: 'GET', path: '/api/providers/{providerId}' },
    inputSchema: objectSchema({ providerId: STRING_SCHEMA }, ['providerId']),
    outputSchema: PROVIDER_RUNTIME_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'providers.usage.get',
    title: 'Provider Usage',
    description: 'Return usage and pricing posture for a single provider.',
    category: 'providers',
    scopes: ['read:providers'],
    http: { method: 'GET', path: '/api/providers/{providerId}/usage' },
    inputSchema: objectSchema({ providerId: STRING_SCHEMA }, ['providerId']),
    outputSchema: PROVIDER_USAGE_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'settings.snapshot',
    title: 'Settings Snapshot',
    description: 'Return the settings integration snapshot.',
    category: 'settings',
    scopes: ['read:settings'],
    http: { method: 'GET', path: '/api/settings' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: SETTINGS_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'security.settings',
    title: 'Security Settings Report',
    description: 'Return security-relevant settings, defaults, current state, and enablement tradeoffs.',
    category: 'settings',
    scopes: ['read:settings'],
    http: { method: 'GET', path: '/api/security-settings' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: SECURITY_SETTINGS_REPORT_SCHEMA,
  }),
  methodDescriptor({
    id: 'continuity.snapshot',
    title: 'Continuity Snapshot',
    description: 'Return the continuity integration snapshot.',
    category: 'continuity',
    scopes: ['read:continuity'],
    http: { method: 'GET', path: '/api/continuity' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: CONTINUITY_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'worktrees.snapshot',
    title: 'Worktrees Snapshot',
    description: 'Return the worktree integration snapshot.',
    category: 'worktrees',
    scopes: ['read:worktrees'],
    http: { method: 'GET', path: '/api/worktrees' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: WORKTREE_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'intelligence.snapshot',
    title: 'Intelligence Snapshot',
    description: 'Return the intelligence integration snapshot.',
    category: 'intelligence',
    scopes: ['read:intelligence'],
    http: { method: 'GET', path: '/api/intelligence' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: INTELLIGENCE_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'memory.doctor',
    title: 'Memory Doctor',
    description: 'Return sqlite-vec and memory embedding-provider diagnostics.',
    category: 'memory',
    scopes: ['read:memory'],
    http: { method: 'GET', path: '/api/memory/doctor' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: MEMORY_DOCTOR_REPORT_SCHEMA,
  }),
  methodDescriptor({
    id: 'memory.vector.stats',
    title: 'Memory Vector Stats',
    description: 'Return the current sqlite-vec vector-store posture.',
    category: 'memory',
    scopes: ['read:memory'],
    http: { method: 'GET', path: '/api/memory/vector' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: objectSchema({ vector: MEMORY_VECTOR_STATS_SCHEMA }, ['vector']),
  }),
  methodDescriptor({
    id: 'memory.vector.rebuild',
    title: 'Rebuild Memory Vector Index',
    description: 'Rebuild the sqlite-vec vector index.',
    category: 'memory',
    scopes: ['write:memory'],
    access: 'admin',
    http: { method: 'POST', path: '/api/memory/vector/rebuild' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: objectSchema({ vector: MEMORY_VECTOR_STATS_SCHEMA }, ['vector']),
  }),
  methodDescriptor({
    id: 'memory.embeddings.default.set',
    title: 'Set Default Memory Embedding Provider',
    description: 'Set the active default memory embedding provider.',
    category: 'memory',
    scopes: ['write:memory'],
    access: 'admin',
    http: { method: 'POST', path: '/api/memory/embeddings/default' },
    inputSchema: bodyEnvelopeSchema({ providerId: STRING_SCHEMA }, ['providerId']),
    outputSchema: MEMORY_DOCTOR_REPORT_SCHEMA,
  }),
  methodDescriptor({
    id: 'scheduler.capacity',
    title: 'Scheduler Capacity',
    description: 'Return the current automation-scheduler capacity snapshot: total slots, in-use slots, queue depth, and age of the oldest queued run.',
    category: 'scheduler',
    scopes: ['read:automation'],
    http: { method: 'GET', path: '/api/runtime/scheduler' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: objectSchema({
      slotsTotal: NUMBER_SCHEMA,
      slotsInUse: NUMBER_SCHEMA,
      queueDepth: NUMBER_SCHEMA,
      oldestQueuedAgeMs: nullableSchema(NUMBER_SCHEMA),
    }, ['slotsTotal', 'slotsInUse', 'queueDepth', 'oldestQueuedAgeMs']),
  }),
];
