/**
 * method-catalog-fleet.ts
 *
 * (see CHANGELOG 1.0.0) — fleet.* + checkpoints.* method descriptors. Split out of
 * method-catalog-control-core.ts (which was already at the 800-line
 * source-file cap) rather than grown into it, mirroring how
 * method-catalog-control-automation.ts is a sibling split of the same file
 * merged back in by method-catalog-control.ts.
 *
 * Thin read (fleet) / checkpoint-lifecycle verbs over managers the daemon
 * ALREADY holds in-process (ProcessRegistry, WorkspaceCheckpointManager —
 * see routes/fleet.ts and routes/checkpoints.ts header comments). No `http`
 * REST path is bound: these are registered with a direct handler on the
 * catalog (RuntimeServices construction, ../runtime/services.ts).
 * `transport: ['ws']` with no `http` binding is the transport-parity gate's
 * (test/transport-parity.test.ts) own sanctioned category for a method
 * dispatchable ONLY via the generic invoke-by-id mechanism — see the
 * TRANSPORT NOTE above `sessions.search` in method-catalog-control-core.ts
 * for the full rationale (this block predates that comment only in file
 * position, not in reasoning).
 */
import type { GatewayMethodDescriptor } from './method-catalog-shared.js';
import { EMPTY_OBJECT_SCHEMA, methodDescriptor } from './method-catalog-shared.js';
import {
  CHECKPOINTS_CREATE_INPUT_SCHEMA,
  CHECKPOINTS_CREATE_OUTPUT_SCHEMA,
  CHECKPOINTS_DIFF_INPUT_SCHEMA,
  CHECKPOINTS_DIFF_OUTPUT_SCHEMA,
  CHECKPOINTS_LIST_INPUT_SCHEMA,
  CHECKPOINTS_LIST_OUTPUT_SCHEMA,
  CHECKPOINTS_RESTORE_INPUT_SCHEMA,
  CHECKPOINTS_RESTORE_OUTPUT_SCHEMA,
  CHECKPOINTS_RESTORE_PREVIEW_INPUT_SCHEMA,
  CHECKPOINTS_RESTORE_PREVIEW_OUTPUT_SCHEMA,
  CHECKPOINTS_REVERT_HUNK_INPUT_SCHEMA,
  CHECKPOINTS_REVERT_HUNK_OUTPUT_SCHEMA,
  CHECKPOINTS_REVERT_HUNK_PREVIEW_INPUT_SCHEMA,
  CHECKPOINTS_REVERT_HUNK_PREVIEW_OUTPUT_SCHEMA,
  FLEET_ATTEMPTS_JUDGE_INPUT_SCHEMA,
  FLEET_ATTEMPTS_JUDGE_OUTPUT_SCHEMA,
  FLEET_ATTEMPTS_LIST_INPUT_SCHEMA,
  FLEET_ATTEMPTS_LIST_OUTPUT_SCHEMA,
  FLEET_CONFLICTS_LIST_INPUT_SCHEMA,
  FLEET_CONFLICTS_LIST_OUTPUT_SCHEMA,
  FLEET_CONFLICTS_RESOLVE_INPUT_SCHEMA,
  FLEET_CONFLICTS_RESOLVE_OUTPUT_SCHEMA,
  FLEET_ATTEMPTS_PICK_INPUT_SCHEMA,
  FLEET_ATTEMPTS_PICK_OUTPUT_SCHEMA,
  FLEET_ARCHIVE_FINISHED_OUTPUT_SCHEMA,
  FLEET_ARCHIVE_INPUT_SCHEMA,
  FLEET_ARCHIVE_OUTPUT_SCHEMA,
  FLEET_ARCHIVED_LIST_OUTPUT_SCHEMA,
  FLEET_LIST_INPUT_SCHEMA,
  FLEET_LIST_OUTPUT_SCHEMA,
  FLEET_SNAPSHOT_OUTPUT_SCHEMA,
  FLEET_UNARCHIVE_OUTPUT_SCHEMA,
} from './operator-contract-schemas.js';

export const builtinGatewayFleetMethodDescriptors: readonly GatewayMethodDescriptor[] = [
  methodDescriptor({
    id: 'fleet.snapshot',
    title: 'Fleet Snapshot',
    description: 'Return a point-in-time capture of every live/completed runtime process (agents, WRFC chains/subtasks, workflow FSMs/triggers/schedules, watchers, background processes) as a flat, parentId-linked node list. Capped at 2000 nodes (truncated:true + totalCount when the live fleet exceeds the cap) — use fleet.list to page through a larger fleet.',
    category: 'fleet',
    scopes: ['read:fleet'],
    transport: ['ws'],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: FLEET_SNAPSHOT_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'fleet.list',
    title: 'List Fleet Processes',
    description: 'Paginated, filtered (kinds/states) query over the live process registry. Cursor pagination returns disjoint pages that union to the full matching set at query time.',
    category: 'fleet',
    scopes: ['read:fleet'],
    transport: ['ws'],
    inputSchema: FLEET_LIST_INPUT_SCHEMA,
    outputSchema: FLEET_LIST_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'fleet.archive',
    title: 'Archive Finished Fleet Subtree',
    description: 'Move one FINISHED process subtree (root id + all descendants, every node terminal) out of the live fleet view into the session archive. Honest refusal (archived:false + reason) for an unknown id or a subtree with live members. Archived nodes stay inspectable via fleet.archived.list.',
    category: 'fleet',
    scopes: ['write:fleet'],
    transport: ['ws'],
    inputSchema: FLEET_ARCHIVE_INPUT_SCHEMA,
    outputSchema: FLEET_ARCHIVE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'fleet.unarchive',
    title: 'Restore Archived Fleet Subtree',
    description: 'Return an archived subtree to the live fleet view. Returns the number of nodes restored (0 when nothing under the id was archived).',
    category: 'fleet',
    scopes: ['write:fleet'],
    transport: ['ws'],
    inputSchema: FLEET_ARCHIVE_INPUT_SCHEMA,
    outputSchema: FLEET_UNARCHIVE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'fleet.archiveFinished',
    title: 'Archive All Finished Fleet Subtrees',
    description: 'Archive every root subtree whose nodes are all terminal (done/failed/killed/interrupted). A finished member of a still-running swarm stays with its parent. Returns the number of nodes archived.',
    category: 'fleet',
    scopes: ['write:fleet'],
    transport: ['ws'],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: FLEET_ARCHIVE_FINISHED_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'fleet.archived.list',
    title: 'List Archived Fleet Processes',
    description: 'Return the session-archived process nodes (same node shape as fleet.snapshot; still live-derived from the source managers, so usage/cost stay current).',
    category: 'fleet',
    scopes: ['read:fleet'],
    transport: ['ws'],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: FLEET_ARCHIVED_LIST_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'fleet.attempts.list',
    title: 'List Best-of-N Held-Merge Groups',
    description: 'Return the best-of-N attempt groups whose siblings ran in isolated worktrees and are HELD for a winner pick instead of auto-merging (optionally filtered to one workstream). Each group lists its candidates with their per-attempt diff, usage, and outcome, plus any prior judge proposal. Read-only.',
    category: 'fleet',
    scopes: ['read:fleet'],
    transport: ['ws'],
    inputSchema: FLEET_ATTEMPTS_LIST_INPUT_SCHEMA,
    outputSchema: FLEET_ATTEMPTS_LIST_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'fleet.attempts.pick',
    title: 'Pick a Best-of-N Winner',
    description: 'Accept one attempt as the winner of its best-of-N group: its worktree branch is merged through the existing sequential integration lane and every losing sibling\'s worktree is cleaned. The winner must be a held (passed) candidate of a group whose siblings are all terminal — an unknown/not-ready group or an invalid winner is an honest 409, never a partial merge.',
    category: 'fleet',
    scopes: ['write:fleet'],
    dangerous: true,
    transport: ['ws'],
    inputSchema: FLEET_ATTEMPTS_PICK_INPUT_SCHEMA,
    outputSchema: FLEET_ATTEMPTS_PICK_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'fleet.attempts.judge',
    title: 'Propose a Best-of-N Winner (Model Judgment)',
    description: 'Run the optional judge model over a best-of-N group\'s candidates and PROPOSE a winner, with reasons. The output is explicitly model judgment (scoredBy:"model") — it never auto-picks unless the source item opted into auto-accept; a human still confirms via fleet.attempts.pick. An engine with no judge configured returns an honest 501.',
    category: 'fleet',
    scopes: ['read:fleet'],
    transport: ['ws'],
    inputSchema: FLEET_ATTEMPTS_JUDGE_INPUT_SCHEMA,
    outputSchema: FLEET_ATTEMPTS_JUDGE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'fleet.conflicts.list',
    title: 'List Merge-Conflict Rows',
    description: 'Return every work item whose integration merge CONFLICTED and is waiting on a human: the kept worktree path, item branch, the STRUCTURED conflicting-file list, and the resolution session id once one was spawned. Optionally filtered to one workstream. Read-only.',
    category: 'fleet',
    scopes: ['read:fleet'],
    transport: ['ws'],
    inputSchema: FLEET_CONFLICTS_LIST_INPUT_SCHEMA,
    outputSchema: FLEET_CONFLICTS_LIST_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'fleet.conflicts.resolve',
    title: 'Spawn a Conflict-Resolution Session',
    description: 'The conflict row\'s one action: spawn a resolution session INSIDE the kept worktree, seeded with the structured conflict list and tree path (the same seeded-session machinery as the CI fix flow), and stamp the REAL session id back onto the item. When the resolution lands and the re-merge succeeds, the kept tree is reclaimed automatically. An item with no unresolved conflict is an honest 409.',
    category: 'fleet',
    scopes: ['write:fleet'],
    transport: ['ws'],
    inputSchema: FLEET_CONFLICTS_RESOLVE_INPUT_SCHEMA,
    outputSchema: FLEET_CONFLICTS_RESOLVE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'checkpoints.list',
    title: 'List Workspace Checkpoints',
    description: 'Return workspace checkpoints (whole-workspace filesystem snapshots), newest first, optionally filtered by kind/since and capped by limit.',
    category: 'checkpoints',
    scopes: ['read:checkpoints'],
    transport: ['ws'],
    inputSchema: CHECKPOINTS_LIST_INPUT_SCHEMA,
    outputSchema: CHECKPOINTS_LIST_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'checkpoints.create',
    title: 'Create Workspace Checkpoint',
    description: 'Create a new workspace checkpoint. Returns checkpoint:null, noop:true (not an error) when the workspace tree is identical to the most recent checkpoint — no commit, ref, or manifest entry is created in that case.',
    category: 'checkpoints',
    scopes: ['write:checkpoints'],
    transport: ['ws'],
    inputSchema: CHECKPOINTS_CREATE_INPUT_SCHEMA,
    outputSchema: CHECKPOINTS_CREATE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'checkpoints.diff',
    title: 'Diff Workspace Checkpoints',
    description: 'Diff two checkpoints, or one checkpoint against the live working tree when `b` is omitted. An unknown/gc\'d checkpoint id is an honest 404, not a silent empty diff.',
    category: 'checkpoints',
    scopes: ['read:checkpoints'],
    transport: ['ws'],
    inputSchema: CHECKPOINTS_DIFF_INPUT_SCHEMA,
    outputSchema: CHECKPOINTS_DIFF_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'checkpoints.restore',
    title: 'Restore Workspace Checkpoint',
    description: 'DESTRUCTIVE: restore the workspace to the state captured by a checkpoint (git-backed workspace rewrite). Refuses to run unconfirmed: pass confirm:true to execute immediately, OR a confirmToken from checkpoints.restorePreview. An unconfirmed call returns a structured refusal (result:null, refused:true, refusal naming both options) — not an error. An unknown/gc\'d checkpoint id (once confirmed) is an honest 404, not a silent no-op.',
    category: 'checkpoints',
    scopes: ['write:checkpoints'],
    dangerous: true,
    transport: ['ws'],
    inputSchema: CHECKPOINTS_RESTORE_INPUT_SCHEMA,
    outputSchema: CHECKPOINTS_RESTORE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'checkpoints.restorePreview',
    title: 'Preview Workspace Checkpoint Restore',
    description: 'Read-only: preview what a checkpoints.restore of this checkpoint would change (label, affected-path count + sample, diffstat) and mint a short-lived (~2 min), single-use confirmToken that authorizes the matching restore. No workspace mutation. An unknown/gc\'d checkpoint id is an honest 404.',
    category: 'checkpoints',
    scopes: ['read:checkpoints'],
    transport: ['ws'],
    inputSchema: CHECKPOINTS_RESTORE_PREVIEW_INPUT_SCHEMA,
    outputSchema: CHECKPOINTS_RESTORE_PREVIEW_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'checkpoints.revertHunkPreview',
    title: 'Preview a Single-Hunk Revert',
    description: 'Read-only: check whether reverse-applying ONE unified-diff hunk (copied from a checkpoints.diff / sessions.changes.get diff) to its file in the live working tree would apply cleanly right now, and mint a short-lived (~2 min), single-use confirmToken authorizing the matching checkpoints.revertHunk. A stale/drifted hunk returns applies:false with a human-readable conflict and a null token — an honest "this hunk no longer applies", not an error. No workspace mutation.',
    category: 'checkpoints',
    scopes: ['read:checkpoints'],
    transport: ['ws'],
    inputSchema: CHECKPOINTS_REVERT_HUNK_PREVIEW_INPUT_SCHEMA,
    outputSchema: CHECKPOINTS_REVERT_HUNK_PREVIEW_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'checkpoints.revertHunk',
    title: 'Revert a Single Hunk',
    description: 'DESTRUCTIVE: reverse-apply ONE unified-diff hunk to its file in the live working tree, undoing exactly that hunk and nothing else. The hunk must still apply cleanly in reverse — a stale/drifted hunk is an honest 409 conflict, never a partial write. Refuses to run unconfirmed: pass confirm:true to execute immediately, OR a confirmToken from checkpoints.revertHunkPreview. An unconfirmed call returns a structured refusal (receipt:null, refused:true, refusal naming both options) — not an error. Snapshots the whole tree (a manual checkpoint) before writing, so the revert is itself reversible; returns a receipt whose undo block carries that checkpoint id. Emits a HUNK_REVERTED receipt event.',
    category: 'checkpoints',
    scopes: ['write:checkpoints'],
    dangerous: true,
    transport: ['ws'],
    inputSchema: CHECKPOINTS_REVERT_HUNK_INPUT_SCHEMA,
    outputSchema: CHECKPOINTS_REVERT_HUNK_OUTPUT_SCHEMA,
  }),
];
