import type { GatewayMethodDescriptor } from './method-catalog-shared.js';
import { EMPTY_OBJECT_SCHEMA,STRING_SCHEMA,objectSchema,listOutputSchema,entityOutputSchema,bodyEnvelopeSchema,methodDescriptor } from './method-catalog-shared.js';
import {
  CONFIG_SET_OUTPUT_SCHEMA,
  CONFIG_SNAPSHOT_SCHEMA,
  CREDENTIALS_SNAPSHOT_SCHEMA,
  CREDENTIAL_DELETE_INPUT_SCHEMA,
  CREDENTIAL_DELETE_OUTPUT_SCHEMA,
  CREDENTIAL_SET_INPUT_SCHEMA,
  CREDENTIAL_SET_OUTPUT_SCHEMA,
  LOCAL_AUTH_USER_SCHEMA,
  LOCAL_AUTH_BOOTSTRAP_DELETE_OUTPUT_SCHEMA,
  LOCAL_AUTH_DELETE_OUTPUT_SCHEMA,
  LOCAL_AUTH_SESSION_REVOKE_OUTPUT_SCHEMA,
  LOCAL_AUTH_STATUS_SCHEMA,
  LOCAL_AUTH_ROTATE_PASSWORD_OUTPUT_SCHEMA,
  PANEL_OPEN_OUTPUT_SCHEMA,
  PANEL_SNAPSHOT_SCHEMA,
} from './operator-contract-schemas.js';

export const builtinGatewayAdminMethodDescriptors: readonly GatewayMethodDescriptor[] = [
  methodDescriptor({
    id: 'local_auth.status',
    title: 'Local Auth Status',
    description: 'Return local auth posture, users, and sessions.',
    category: 'auth',
    scopes: ['read:auth'],
    access: 'admin',
    http: { method: 'GET', path: '/api/local-auth' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: LOCAL_AUTH_STATUS_SCHEMA,
  }),
  methodDescriptor({
    id: 'local_auth.users.create',
    title: 'Create Local Auth User',
    description: 'Create a local auth user.',
    category: 'auth',
    scopes: ['write:auth'],
    access: 'admin',
    http: { method: 'POST', path: '/api/local-auth/users' },
    inputSchema: bodyEnvelopeSchema({
      username: STRING_SCHEMA,
      password: STRING_SCHEMA,
    }, ['username', 'password']),
    outputSchema: entityOutputSchema('user', LOCAL_AUTH_USER_SCHEMA),
  }),
  methodDescriptor({
    id: 'local_auth.users.delete',
    title: 'Delete Local Auth User',
    description: 'Delete a local auth user.',
    category: 'auth',
    scopes: ['write:auth'],
    access: 'admin',
    http: { method: 'DELETE', path: '/api/local-auth/users/{username}' },
    inputSchema: objectSchema({ username: STRING_SCHEMA }, ['username']),
    outputSchema: LOCAL_AUTH_DELETE_OUTPUT_SCHEMA,
    dangerous: true,
  }),
  methodDescriptor({
    id: 'local_auth.users.password.rotate',
    title: 'Rotate Local Auth Password',
    description: 'Rotate a local auth user password.',
    category: 'auth',
    scopes: ['write:auth'],
    access: 'admin',
    http: { method: 'POST', path: '/api/local-auth/users/{username}/password' },
    inputSchema: bodyEnvelopeSchema({ password: STRING_SCHEMA }, ['password']),
    outputSchema: LOCAL_AUTH_ROTATE_PASSWORD_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'local_auth.sessions.delete',
    title: 'Revoke Local Auth Session',
    description: 'Revoke a local auth session.',
    category: 'auth',
    scopes: ['write:auth'],
    access: 'admin',
    http: { method: 'DELETE', path: '/api/local-auth/sessions/{sessionId}' },
    inputSchema: objectSchema({ sessionId: STRING_SCHEMA }, ['sessionId']),
    outputSchema: LOCAL_AUTH_SESSION_REVOKE_OUTPUT_SCHEMA,
    dangerous: true,
  }),
  methodDescriptor({
    id: 'local_auth.bootstrap.delete',
    title: 'Delete Bootstrap File',
    description: 'Delete the local-auth bootstrap credential file.',
    category: 'auth',
    scopes: ['write:auth'],
    access: 'admin',
    http: { method: 'DELETE', path: '/api/local-auth/bootstrap-file' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: LOCAL_AUTH_BOOTSTRAP_DELETE_OUTPUT_SCHEMA,
    dangerous: true,
  }),
  methodDescriptor({
    id: 'panels.list',
    title: 'List Panels',
    description: 'Return integration panel descriptors.',
    category: 'panels',
    scopes: ['read:panels'],
    http: { method: 'GET', path: '/api/panels' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('panels', PANEL_SNAPSHOT_SCHEMA),
  }),
  methodDescriptor({
    id: 'panels.open',
    title: 'Open Panel',
    description: 'Request that a panel be opened in the current TUI session.',
    category: 'panels',
    scopes: ['write:panels'],
    http: { method: 'POST', path: '/api/panels/open' },
    inputSchema: bodyEnvelopeSchema({
      id: STRING_SCHEMA,
      pane: STRING_SCHEMA,
    }, ['id']),
    outputSchema: PANEL_OPEN_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'config.get',
    title: 'Get Config',
    description: 'Return the resolved GoodVibes config snapshot.',
    category: 'config',
    scopes: ['read:config'],
    access: 'admin',
    http: { method: 'GET', path: '/config' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: CONFIG_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'credentials.get',
    title: 'Get Credential Status',
    description: 'Return secret-free credential status (configured/usable) for the shared store. Never returns raw secret bytes. Optional ?key= narrows to one credential.',
    category: 'config',
    scopes: ['read:config'],
    access: 'admin',
    http: { method: 'GET', path: '/config/credentials' },
    inputSchema: objectSchema({ key: STRING_SCHEMA }, []),
    outputSchema: CREDENTIALS_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'credentials.set',
    title: 'Set Credential',
    description: 'Store a credential for a secret-bearing config key THROUGH the daemon, so a surface no longer has to write it into its own on-disk secret store, the write counterpart to credentials.get, and the reason a client on another machine can now finish a settings modal at all. `key` is the config path (e.g. surfaces.telegram.botToken); the secret-store name is derived from it. The value goes into the encrypted store at the scope the ownership rules resolve (a daemon-needed credential lands in the daemon tier whoever asked), is read BACK and compared, and only then does the config key take its goodvibes://secrets/goodvibes/<KEY> reference. A read-back mismatch fails the call and leaves the setting exactly as it was, because a reference resolving to nothing reads as a configured-but-broken credential. The response is secret-free: key names, the resolved scope, the reference now in config, and two plain sentences about where the setting and the credential are filed, never the value. Refuses a key that is not credential-bearing (use config.set) and refuses a value that is itself a goodvibes:// reference. ws-only invoke verb; no REST binding. Mutating, so a relay call is covered by relay.requireStepUpForMutations exactly as config.set is.',
    category: 'config',
    scopes: ['write:config'],
    access: 'admin',
    transport: ['ws'],
    inputSchema: CREDENTIAL_SET_INPUT_SCHEMA,
    outputSchema: CREDENTIAL_SET_OUTPUT_SCHEMA,
    dangerous: true,
  }),
  methodDescriptor({
    id: 'credentials.delete',
    title: 'Delete Credential',
    description: 'Remove a credential: the stored secret first, then the config reference pointing at it. That order is deliberate, clearing the config first would strand a secret nothing points at and nothing reaps, while this order leaves, for an instant, a reference resolving to nothing, which every reader already treats as configured-but-broken (the honest state for a credential mid-removal). `cleared: false` means nothing was stored under that key: a miss, not an error, because asking for a credential to be gone when it already is has succeeded. ws-only invoke verb; no REST binding. Mutating, so a relay call is covered by relay.requireStepUpForMutations exactly as config.set is.',
    category: 'config',
    scopes: ['write:config'],
    access: 'admin',
    transport: ['ws'],
    inputSchema: CREDENTIAL_DELETE_INPUT_SCHEMA,
    outputSchema: CREDENTIAL_DELETE_OUTPUT_SCHEMA,
    dangerous: true,
  }),
  methodDescriptor({
    id: 'config.set',
    title: 'Set Config Value',
    description: 'Set a config value through the daemon API.',
    category: 'config',
    scopes: ['write:config'],
    access: 'admin',
    http: { method: 'POST', path: '/config' },
    inputSchema: bodyEnvelopeSchema({
      key: STRING_SCHEMA,
    }, ['key']),
    outputSchema: CONFIG_SET_OUTPUT_SCHEMA,
  }),
];
