export type { ConfigManagerLike } from './sandbox/manager.js';
export {
  buildSandboxReview,
  detectSandboxHostStatus,
  getSandboxConfigSnapshot,
  getSandboxPreset,
  inspectSandboxBundle,
  inspectSandboxProbe,
  inspectSandboxSessionArtifact,
  isRunningInWsl,
  listSandboxPresets,
  listSandboxProfiles,
  renderSandboxPresets,
  renderSandboxProfiles,
  renderSandboxRecommendation,
  renderSandboxReview,
  renderSandboxSessions,
} from './sandbox/manager.js';
export { SandboxSessionRegistry } from './sandbox/session-registry.js';
export type {
  ManagedSettingsBundle,
  ProfileBundleEntry,
  ProfileSyncBundle,
  SandboxBackendAvailability,
  SandboxBackendProbe,
  SandboxBundle,
  SandboxConfigSnapshot,
  SandboxEvalIsolationMode,
  SandboxHostStatus,
  SandboxLaunchPlan,
  SandboxMcpIsolationMode,
  SandboxPreset,
  SandboxProbe,
  SandboxProfile,
  SandboxQemuSessionMode,
  SandboxResolvedBackend,
  SandboxReview,
  SandboxSession,
  SandboxSessionArtifact,
  SandboxSessionKind,
  SandboxSessionState,
  SandboxVmBackend,
  SandboxWindowsMode,
} from './sandbox/types.js';
