/**
 * daemon-stub-handlers.ts
 *
 * Shared helper for router-e2e tests.
 * Exports makeDefaultDaemonHandlerStub() which returns a full no-op
 * implementation of DaemonApiRouteHandlers. Tests import this and spread
 * targeted overrides, eliminating the ~190-line inline stubs that were
 * previously duplicated across control and telemetry test files.
 */

import type { DaemonApiRouteHandlers } from '../../packages/sdk/src/_internal/daemon/context.js';

export function makeDefaultDaemonHandlerStub(
  overrides: Partial<DaemonApiRouteHandlers> = {},
): DaemonApiRouteHandlers {
  const noop = () => { throw new Error('unexpected handler call'); };

  const defaults: Partial<DaemonApiRouteHandlers> = {
    getStatus: () =>
      Response.json({ ok: true, version: '0.0.0-test', uptime: 0 }),

    getCurrentAuth: () =>
      Response.json({ authenticated: false }),

    getControlPlaneSnapshot: () =>
      Response.json({
        totals: { clients: 0, activeClients: 0, surfaceMessages: 0, recentEvents: 0, requests: 0, errors: 0 },
        server: { port: 9000, enabled: true, host: '127.0.0.1' },
      }),

    getOperatorContract: () =>
      Response.json({ methods: [], version: '0.0.0-test' }),

    getControlPlaneRecentEvents: (limit: number) =>
      Response.json({ events: [], limit }),

    getControlPlaneMessages: () =>
      Response.json({ messages: [] }),

    getControlPlaneClients: () =>
      Response.json({ clients: [] }),

    getControlPlaneWeb: () =>
      new Response('<html>control</html>', { headers: { 'content-type': 'text/html' } }),

    getTelemetrySnapshot: () => Response.json({ events: [], version: 1 }),
    getTelemetryEvents: () => Response.json({ items: [] }),
    getTelemetryErrors: () => Response.json({ items: [] }),
    getTelemetryTraces: () => Response.json({ items: [] }),
    getTelemetryMetrics: () => Response.json({ runtime: {}, sessionMetrics: {} }),
    createTelemetryEventStream: () => new Response('', { status: 200 }),
    getTelemetryOtlpTraces: () => Response.json({}),
    getTelemetryOtlpLogs: () => Response.json({}),
    getTelemetryOtlpMetrics: () => Response.json({}),
    postTelemetryOtlpLogs: () => Response.json({ partialSuccess: {} }),
    postTelemetryOtlpTraces: () => Response.json({ partialSuccess: {} }),
    postTelemetryOtlpMetrics: () => Response.json({ partialSuccess: {} }),

    getGatewayMethods: () => Response.json({ methods: [] }),
    getGatewayEvents: () => Response.json({ events: [] }),
    getGatewayMethod: () => Response.json(null),
    invokeGatewayMethod: () => Response.json({ ok: false }),
    createControlPlaneEventStream: () => new Response('', { status: 200 }),
    getRoutesSnapshot: () => Response.json({ routes: [] }),
    getSurfaces: () => Response.json({ surfaces: [] }),
    getChannelAccounts: () => Response.json({ accounts: [] }),
    getChannelSurfaceAccounts: () => Response.json({ accounts: [] }),
    getChannelAccount: () => Response.json(null),
    postChannelAccountAction: noop as never,
    getChannelSetupSchema: () => Response.json({}),
    getChannelDoctor: () => Response.json({ issues: [] }),
    getChannelRepairActions: () => Response.json({ actions: [] }),
    getChannelLifecycle: () => Response.json({}),
    postChannelLifecycleMigrate: () => Response.json({ ok: true }),
    getChannelCapabilities: () => Response.json({ capabilities: [] }),
    getChannelSurfaceCapabilities: () => Response.json({ capabilities: [] }),
    getChannelTools: () => Response.json({ tools: [] }),
    getChannelSurfaceTools: () => Response.json({ tools: [] }),
    getChannelAgentTools: () => Response.json({ tools: [] }),
    getChannelSurfaceAgentTools: () => Response.json({ tools: [] }),
    postChannelTool: () => Response.json({ ok: true }),
    getChannelActions: () => Response.json({ actions: [] }),
    getChannelSurfaceActions: () => Response.json({ actions: [] }),
    postChannelAction: () => Response.json({ ok: true }),
    postChannelResolveTarget: () => Response.json({ targets: [] }),
    postChannelAuthorize: () => Response.json({ ok: true }),
    postChannelAllowlistResolve: () => Response.json({ entries: [] }),
    postChannelAllowlistEdit: () => Response.json({ ok: true }),
    getChannelPolicies: () => Response.json({ policies: [] }),
    postChannelPolicy: () => Response.json({ ok: true }),
    patchChannelPolicy: () => Response.json({ ok: true }),
    getChannelPolicyAudit: () => Response.json({ entries: [] }),
    getChannelStatus: () => Response.json({ ok: true }),
    getChannelDirectory: () => Response.json({ entries: [] }),
    getWatchers: () => Response.json({ watchers: [] }),
    postWatcher: () => Response.json({ id: 'w-1' }),
    patchWatcher: () => Response.json({ ok: true }),
    watcherAction: () => Response.json({ ok: true }),
    deleteWatcher: () => Response.json({ ok: true }),
    getServiceStatus: () => Response.json({ services: [] }),
    installService: () => Response.json({ ok: true }),
    startService: () => Response.json({ ok: true }),
    stopService: () => Response.json({ ok: true }),
    restartService: () => Response.json({ ok: true }),
    uninstallService: () => Response.json({ ok: true }),
    getRouteBindings: () => Response.json({ bindings: [] }),
    postRouteBinding: () => Response.json({ id: 'rb-1' }),
    patchRouteBinding: () => Response.json({ ok: true }),
    deleteRouteBinding: () => Response.json({ ok: true }),
    getApprovals: () => Response.json({ approvals: [] }),
    approvalAction: () => Response.json({ ok: true }),
    getRemote: () => Response.json({ peers: [] }),
    getRemotePairRequests: () => Response.json({ requests: [] }),
    approveRemotePairRequest: () => Response.json({ ok: true }),
    rejectRemotePairRequest: () => Response.json({ ok: true }),
    getRemotePeers: () => Response.json({ peers: [] }),
    rotateRemotePeerToken: () => Response.json({ token: 'new-token' }),
    revokeRemotePeerToken: () => Response.json({ ok: true }),
    disconnectRemotePeer: () => Response.json({ ok: true }),
    getRemoteWork: () => Response.json({ work: [] }),
    invokeRemotePeer: () => Response.json({ ok: true }),
    cancelRemoteWork: () => Response.json({ ok: true }),
    getHealth: () => Response.json({ healthy: true }),
    getAccounts: () => Response.json({ accounts: [] }),
    getProviders: () => Response.json({ providers: [] }),
    getProvider: () => Response.json(null),
    getProviderUsage: () => Response.json(null),
    getSettings: () => Response.json({ settings: {} }),
    getContinuity: () => Response.json({ continuity: {} }),
    getWorktrees: () => Response.json({ worktrees: [] }),
    getIntelligence: () => Response.json({ intelligence: {} }),
    getLocalAuth: () => Response.json({ users: [] }),
    postLocalAuthUser: () => Response.json({ ok: true }),
    deleteLocalAuthUser: () => Response.json({ ok: true }),
    postLocalAuthPassword: () => Response.json({ ok: true }),
    deleteLocalAuthSession: () => Response.json({ ok: true }),
    deleteBootstrapFile: () => Response.json({ ok: true }),
    getPanels: () => Response.json({ panels: [] }),
    postPanelOpen: () => Response.json({ ok: true }),
    getEvents: () => Response.json({ events: [] }),
    getConfig: () => Response.json({ config: {} }),
    postConfig: () => Response.json({ ok: true }),
    getReview: () => Response.json({ review: {} }),
    getIntegrationSession: () => Response.json({}),
    getIntegrationTasks: () => Response.json({ tasks: [] }),
    getIntegrationAutomation: () => Response.json({}),
    getIntegrationSessions: () => Response.json({ sessions: [] }),
    getAutomationHeartbeat: () => Response.json({}),
    postAutomationHeartbeat: () => Response.json({ ok: true }),
    getMemoryDoctor: () => Response.json({}),
    getMemoryVectorStats: () => Response.json({}),
    postMemoryVectorRebuild: () => Response.json({ ok: true }),
    postMemoryEmbeddingDefault: () => Response.json({ ok: true }),
    getKnowledgeStatus: () => Response.json({}),
    getKnowledgeSources: () => Response.json({ sources: [] }),
    getKnowledgeNodes: () => Response.json({ nodes: [] }),
    getKnowledgeIssues: () => Response.json({ issues: [] }),
    getKnowledgeItem: () => Response.json(null),
    getKnowledgeConnectors: () => Response.json({ connectors: [] }),
    getKnowledgeConnector: () => Response.json(null),
    getKnowledgeConnectorDoctor: () => Response.json({}),
    getKnowledgeProjectionTargets: () => Response.json({ targets: [] }),
    getKnowledgeGraphqlSchema: () => Response.json({ schema: '' }),
    getKnowledgeExtractions: () => Response.json({ extractions: [] }),
    getKnowledgeUsage: () => Response.json({}),
    getKnowledgeCandidates: () => Response.json({ candidates: [] }),
    getKnowledgeCandidate: () => Response.json(null),
    getKnowledgeReports: () => Response.json({ reports: [] }),
    getKnowledgeReport: () => Response.json(null),
    getKnowledgeExtraction: () => Response.json(null),
    getKnowledgeSourceExtraction: () => Response.json(null),
    getKnowledgeJobs: () => Response.json({ jobs: [] }),
    getKnowledgeJob: () => Response.json(null),
    getKnowledgeJobRuns: () => Response.json({ runs: [] }),
    getKnowledgeSchedules: () => Response.json({ schedules: [] }),
    getKnowledgeSchedule: () => Response.json(null),
    postKnowledgeIngestUrl: () => Response.json({ ok: true }),
    postKnowledgeIngestArtifact: () => Response.json({ ok: true }),
    postKnowledgeImportBookmarks: () => Response.json({ ok: true }),
    postKnowledgeImportUrls: () => Response.json({ ok: true }),
    postKnowledgeIngestConnector: () => Response.json({ ok: true }),
    postKnowledgeSearch: () => Response.json({ results: [] }),
    postKnowledgePacket: () => Response.json({ ok: true }),
    postKnowledgeDecideCandidate: () => Response.json({ ok: true }),
    postKnowledgeRunJob: () => Response.json({ ok: true }),
    postKnowledgeLint: () => Response.json({ ok: true }),
    postKnowledgeReindex: () => Response.json({ ok: true }),
    postKnowledgeSaveSchedule: () => Response.json({ ok: true }),
    deleteKnowledgeSchedule: () => Response.json({ ok: true }),
    postKnowledgeSetScheduleEnabled: () => Response.json({ ok: true }),
    postKnowledgeRenderProjection: () => Response.json({ ok: true }),
    postKnowledgeMaterializeProjection: () => Response.json({ ok: true }),
    executeKnowledgeGraphql: () => Response.json({ data: null }),
    getVoiceStatus: () => Response.json({}),
    getVoiceProviders: () => Response.json({ providers: [] }),
    getVoiceVoices: () => Response.json({ voices: [] }),
    postVoiceTts: () => new Response(new Uint8Array(), { headers: { 'content-type': 'audio/mpeg' } }),
    postVoiceStt: () => Response.json({ text: '' }),
    postVoiceRealtimeSession: () => Response.json({}),
    getWebSearchProviders: () => Response.json({ providers: [] }),
    postWebSearch: () => Response.json({ results: [] }),
    getArtifacts: () => Response.json({ artifacts: [] }),
    postArtifact: () => Response.json({ id: 'art-1' }),
    getArtifact: () => Response.json(null),
    getArtifactContent: () => new Response('', { status: 200 }),
    getMediaProviders: () => Response.json({ providers: [] }),
    postMediaAnalyze: () => Response.json({}),
    postMediaTransform: () => Response.json({}),
    postMediaGenerate: () => Response.json({}),
    getMultimodalStatus: () => Response.json({}),
    getMultimodalProviders: () => Response.json({ providers: [] }),
    postMultimodalAnalyze: () => Response.json({}),
    postMultimodalPacket: () => Response.json({}),
    postMultimodalWriteback: () => Response.json({ ok: true }),
    getRemoteNodeHostContract: () => Response.json({}),
    getSchedulerCapacity: () => Response.json({ capacity: 0 }),
    getRuntimeMetrics: () => Response.json({ metrics: {} }),
    getRuntimeTask: () => Response.json(null),
    runtimeTaskAction: () => Response.json({ ok: true }),
    getTaskStatus: () => Response.json({ status: 'pending' }),
    postTask: async () => Response.json({ taskId: 'task-stub' }),
  };

  return { ...defaults, ...overrides } as DaemonApiRouteHandlers;
}
