#!/usr/bin/env bun
/**
 * check-foundation-io-types.ts
 *
 * A scoped consistency check (and generator) for the OperatorMethodInputMap
 * / OperatorMethodOutputMap entries of the four families that were generic
 * ({[k]:unknown}/unknown) until this change: fleet.*, checkpoints.*,
 * sessions.search, sessions.detach.
 *
 * WHY THIS EXISTS: scripts/export-foundation-artifacts.ts — the script that
 * originally generated packages/contracts/src/generated/foundation-client-types.ts
 * (per that file's own "Generated by ..." header) — is not present anywhere in
 * this repository (no working-tree file, no git history, no package.json
 * reference). It could not be located or restored. Per that decision
 * record (see CHANGELOG 1.0.0), the fallback is to hand-author the four families' InputMap/OutputMap
 * entries from the authoritative method-catalog schemas (mirroring the
 * already-committed approvals.* shape) WITH a mandatory consistency check that
 * proves the hand-authored entries cannot silently drift from those schemas.
 * This script IS that check: it renders the current schema objects into the
 * same TS-type-string convention used throughout foundation-client-types.ts
 * (verified against dozens of existing entries — see the render* functions
 * below for the specific rules and their evidence) and diffs the render
 * against what's actually committed for each covered method's two map entries
 * (input+output; see ENTRIES below for the covered set — the original four
 * typed-I/O families plus the delete-honesty verbs, see CHANGELOG 1.0.0).
 *
 * Usage:
 *   bun run scripts/check-foundation-io-types.ts          # print rendered entries
 *   bun run scripts/check-foundation-io-types.ts --check   # exit 1 on drift
 *
 * Scope: intentionally NOT a general JSON-Schema-to-TS compiler. It only
 * implements the constructs actually present in the four target schemas:
 * string/number/boolean/null primitives, sorted string enums, arrays,
 * nullable (anyOf [X, {type:'null'}]), plain objects with required/optional
 * fields, additionalProperties true/false, and the METADATA_SCHEMA record
 * shape (identity-matched, since its rendering is a fixed, already-repeated
 * literal throughout the file). If a future schema for these method IDs uses
 * a construct this renderer doesn't understand, it throws rather than
 * guessing — a loud failure, not a silent wrong render.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { builtinGatewayControlCompanionMethodDescriptors } from '../packages/sdk/src/platform/control-plane/method-catalog-control-companion.ts';
import { builtinGatewayControlCoreMethodDescriptors } from '../packages/sdk/src/platform/control-plane/method-catalog-control-core.ts';
import {
  EMPTY_OBJECT_SCHEMA,
} from '../packages/sdk/src/platform/control-plane/method-catalog-shared.ts';
import {
  CHECKPOINTS_CREATE_INPUT_SCHEMA,
  CHECKPOINTS_CREATE_OUTPUT_SCHEMA,
  CHECKPOINTS_DIFF_INPUT_SCHEMA,
  CHECKPOINTS_DIFF_OUTPUT_SCHEMA,
  CHECKPOINTS_LIST_INPUT_SCHEMA,
  CHECKPOINTS_LIST_OUTPUT_SCHEMA,
  CHECKPOINTS_RESTORE_INPUT_SCHEMA,
  CHECKPOINTS_RESTORE_OUTPUT_SCHEMA,
  FLEET_LIST_INPUT_SCHEMA,
  FLEET_LIST_OUTPUT_SCHEMA,
  FLEET_SNAPSHOT_OUTPUT_SCHEMA,
  SESSIONS_SEARCH_INPUT_SCHEMA,
  SESSIONS_SEARCH_OUTPUT_SCHEMA,
} from '../packages/sdk/src/platform/control-plane/operator-contract-schemas-fleet.ts';
import { METADATA_SCHEMA } from '../packages/sdk/src/platform/control-plane/operator-contract-schemas-shared.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SDK_ROOT = resolve(__dirname, '..');
const CHECK_ONLY = process.argv.includes('--check');
const FOUNDATION_TYPES_PATH = resolve(
  SDK_ROOT,
  'packages/contracts/src/generated/foundation-client-types.ts',
);

// sessions.detach/delete and companion.chat.sessions.close/delete declare
// their schemas INLINE on their catalog descriptors (no named schema exports)
// — pull them straight off the exported descriptor arrays so the check reads
// the same object the daemon registers, with zero mirroring.
const CATALOG_DESCRIPTORS = [
  ...builtinGatewayControlCoreMethodDescriptors,
  ...builtinGatewayControlCompanionMethodDescriptors,
];

function descriptorSchemas(methodId: string): { input: Record<string, unknown>; output: Record<string, unknown> } {
  const descriptor = CATALOG_DESCRIPTORS.find((d) => d.id === methodId);
  if (!descriptor?.inputSchema || !descriptor.outputSchema) {
    throw new Error(`method-catalog descriptor for "${methodId}" is missing or lacks input/output schemas`);
  }
  return { input: descriptor.inputSchema, output: descriptor.outputSchema };
}

/** Renders a single schema node to the TS type-string convention used in foundation-client-types.ts. */
function renderType(schema: Record<string, unknown>): string {
  // METADATA_SCHEMA (JSON_RECORD_SCHEMA) is rendered as a fixed literal
  // throughout the existing file (verified identical at dozens of call
  // sites, e.g. artifacts.create/get/list, approvals.*, sessions.close, etc).
  if (schema === (METADATA_SCHEMA as unknown as Record<string, unknown>)) {
    return '({  } & { readonly [key: string]: ({  } & { readonly [key: string]: JsonValue }) | boolean | null | number | readonly JsonValue[] | string })';
  }

  if (Array.isArray((schema as { anyOf?: unknown[] }).anyOf)) {
    const branches = (schema as { anyOf: Record<string, unknown>[] }).anyOf;
    if (branches.length === 2 && branches.some((b) => b.type === 'null')) {
      const other = branches.find((b) => b.type !== 'null')!;
      return `null | ${renderType(other)}`;
    }
    throw new Error(`Unsupported anyOf shape: ${JSON.stringify(schema)}`);
  }

  if (schema.type === 'string') {
    if (Array.isArray(schema.enum)) {
      const sorted = [...(schema.enum as string[])].sort();
      return sorted.map((v) => `"${v}"`).join(' | ');
    }
    return 'string';
  }
  if (schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  if (schema.type === 'null') return 'null';

  if (schema.type === 'array') {
    const items = (schema as { items: Record<string, unknown> }).items;
    const itemType = renderType(items);
    const isBarePrimitive =
      (items.type === 'string' && !Array.isArray(items.enum)) ||
      items.type === 'number' ||
      items.type === 'boolean';
    return isBarePrimitive ? `readonly ${itemType}[]` : `readonly (${itemType})[]`;
  }

  if (schema.type === 'object') {
    const properties = (schema.properties ?? {}) as Record<string, Record<string, unknown>>;
    const required = new Set((schema.required as string[] | undefined) ?? []);
    const fields = Object.entries(properties)
      .map(([key, valueSchema]) => {
        const optional = required.has(key) ? '' : '?';
        return `${key}${optional}: ${renderType(valueSchema)};`;
      })
      .join(' ');
    const body = fields.length > 0 ? `{ ${fields} }` : '{  }';
    if (schema.additionalProperties === true) {
      return `(${body} & { readonly [key: string]: unknown })`;
    }
    return body;
  }

  throw new Error(`Unsupported schema node: ${JSON.stringify(schema)}`);
}

const ENTRIES: ReadonlyArray<{ readonly methodId: string; readonly input: Record<string, unknown>; readonly output: Record<string, unknown> }> = [
  { methodId: 'fleet.snapshot', input: EMPTY_OBJECT_SCHEMA, output: FLEET_SNAPSHOT_OUTPUT_SCHEMA },
  { methodId: 'fleet.list', input: FLEET_LIST_INPUT_SCHEMA, output: FLEET_LIST_OUTPUT_SCHEMA },
  { methodId: 'checkpoints.list', input: CHECKPOINTS_LIST_INPUT_SCHEMA, output: CHECKPOINTS_LIST_OUTPUT_SCHEMA },
  { methodId: 'checkpoints.create', input: CHECKPOINTS_CREATE_INPUT_SCHEMA, output: CHECKPOINTS_CREATE_OUTPUT_SCHEMA },
  { methodId: 'checkpoints.diff', input: CHECKPOINTS_DIFF_INPUT_SCHEMA, output: CHECKPOINTS_DIFF_OUTPUT_SCHEMA },
  { methodId: 'checkpoints.restore', input: CHECKPOINTS_RESTORE_INPUT_SCHEMA, output: CHECKPOINTS_RESTORE_OUTPUT_SCHEMA },
  { methodId: 'sessions.search', input: SESSIONS_SEARCH_INPUT_SCHEMA, output: SESSIONS_SEARCH_OUTPUT_SCHEMA },
  { methodId: 'sessions.detach', ...descriptorSchemas('sessions.detach') },
  // Delete-honesty verbs (landed after this check's first cut; covered
  // per the follow-up noted in docs/decisions/2026-07-06-foundation-io-types-hand-authored.md):
  { methodId: 'sessions.delete', ...descriptorSchemas('sessions.delete') },
  { methodId: 'companion.chat.sessions.close', ...descriptorSchemas('companion.chat.sessions.close') },
  { methodId: 'companion.chat.sessions.delete', ...descriptorSchemas('companion.chat.sessions.delete') },
  // Server-side turn stop + steer (SDK 1.4.0):
  { methodId: 'companion.chat.turns.cancel', ...descriptorSchemas('companion.chat.turns.cancel') },
  { methodId: 'companion.chat.messages.steer', ...descriptorSchemas('companion.chat.messages.steer') },
];

const fileText = readFileSync(FOUNDATION_TYPES_PATH, 'utf8');

function extractEntry(map: 'OperatorMethodInputMap' | 'OperatorMethodOutputMap', methodId: string): string | null {
  const escapedId = methodId.replace(/\./g, '\\.');
  const re = new RegExp(`^  "${escapedId}": (.*);$`, 'm');
  const mapStart = fileText.indexOf(`export interface ${map} {`);
  const mapEnd = fileText.indexOf('\n}', mapStart);
  const mapBody = fileText.slice(mapStart, mapEnd);
  const match = mapBody.match(re);
  return match ? match[1] : null;
}

let drifted = false;
const report: string[] = [];

for (const entry of ENTRIES) {
  const expectedInput = renderType(entry.input);
  const expectedOutput = renderType(entry.output);
  const actualInput = extractEntry('OperatorMethodInputMap', entry.methodId);
  const actualOutput = extractEntry('OperatorMethodOutputMap', entry.methodId);

  if (actualInput !== expectedInput) {
    drifted = true;
    report.push(`[drift] OperatorMethodInputMap["${entry.methodId}"]\n  expected: ${expectedInput}\n  actual:   ${actualInput ?? '<missing>'}`);
  }
  if (actualOutput !== expectedOutput) {
    drifted = true;
    report.push(`[drift] OperatorMethodOutputMap["${entry.methodId}"]\n  expected: ${expectedOutput}\n  actual:   ${actualOutput ?? '<missing>'}`);
  }

  if (!CHECK_ONLY) {
    console.log(`  "${entry.methodId}": ${expectedInput};    // -> OperatorMethodInputMap`);
    console.log(`  "${entry.methodId}": ${expectedOutput};    // -> OperatorMethodOutputMap`);
  }
}

if (drifted) {
  console.error(report.join('\n\n'));
  console.error(`\n[check-foundation-io-types] drift detected across ${report.length} entr${report.length === 1 ? 'y' : 'ies'} — regenerate foundation-client-types.ts to match the method-catalog schemas.`);
  if (CHECK_ONLY) process.exit(1);
} else {
  console.log(`[check-foundation-io-types] all ${ENTRIES.length * 2} entries (${ENTRIES.length} methods x input/output) match their source schemas.`);
}
