#!/usr/bin/env bun
/**
 * check-foundation-io-types.ts
 *
 * The consistency check for the OperatorMethodInputMap / OperatorMethodOutputMap
 * entries in packages/contracts/src/generated/foundation-client-types.ts: it
 * proves every entry still says what the method-catalog schema it was rendered
 * from says.
 *
 * WHY THIS EXISTS: scripts/export-foundation-artifacts.ts — the script that
 * originally generated foundation-client-types.ts (per that file's own
 * "Generated by ..." header) — is not present anywhere in this repository (no
 * working-tree file, no git history, no package.json reference). It could not be
 * located or restored. Per that decision record (see CHANGELOG 1.0.0), the
 * fallback was to author the InputMap/OutputMap entries from the authoritative
 * method-catalog schemas WITH a mandatory check proving they cannot silently
 * drift. This script IS that check.
 *
 * SCOPE — every method id in
 * packages/contracts/src/generated/operator-method-ids.ts. It used to carry a
 * hand-maintained ENTRIES list naming 143 of the (then) 443 ids one at a time,
 * which meant the other 300 were unchecked: a corrected `required` array on
 * those catalog schemas changed no consumer type and reddened nothing. The list
 * is now DERIVED from the catalog itself (foundation-io-catalog.ts), so a verb
 * cannot be outside the check — adding one to the catalog adds it here.
 *
 * The rendering rules live in foundation-io-render.ts, shared with
 * scripts/generate-foundation-io-entries.ts (which writes the entries this
 * script verifies), so the writer and the checker cannot disagree about what an
 * entry should look like.
 *
 * Usage:
 *   bun run scripts/check-foundation-io-types.ts          # print rendered entries
 *   bun run scripts/check-foundation-io-types.ts --check   # exit 1 on drift
 */
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { assertCoversMethodIds, descriptorSchemas, parseMethodIds } from './foundation-io-catalog.ts';
import { renderType } from './foundation-io-render.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SDK_ROOT = resolve(__dirname, '..');
const CHECK_ONLY = process.argv.includes('--check');
const FOUNDATION_TYPES_PATH = resolve(
  SDK_ROOT,
  'packages/contracts/src/generated/foundation-client-types.ts',
);
const METHOD_IDS_PATH = resolve(SDK_ROOT, 'packages/contracts/src/generated/operator-method-ids.ts');

const methodIds = parseMethodIds(readFileSync(METHOD_IDS_PATH, 'utf8'));
assertCoversMethodIds(methodIds);

/** Every catalogued verb, each with the schema pair its own descriptor declares. */
const ENTRIES = methodIds.map((methodId) => ({ methodId, ...descriptorSchemas(methodId) }));

const fileText = readFileSync(FOUNDATION_TYPES_PATH, 'utf8');

function extractEntry(map: 'OperatorMethodInputMap' | 'OperatorMethodOutputMap', methodId: string): string | null {
  const escapedId = methodId.replace(/\./g, '\\.');
  const re = new RegExp(`^  "${escapedId}": (.*);$`, 'm');
  const mapStart = fileText.indexOf(`export interface ${map} {`);
  const mapEnd = fileText.indexOf('\n}', mapStart);
  const mapBody = fileText.slice(mapStart, mapEnd);
  const match = mapBody.match(re);
  return match?.[1] ?? null;
}

let drifted = false;
const report: string[] = [];

for (const entry of ENTRIES) {
  const expectedInput = renderType(entry.input);
  const expectedOutput = renderType(entry.output);
  const actualInput = extractEntry('OperatorMethodInputMap', entry.methodId);
  const actualOutput = extractEntry('OperatorMethodOutputMap', entry.methodId);

  if (actualInput !== expectedInput) {
    drifted = true;
    report.push(`[drift] OperatorMethodInputMap["${entry.methodId}"]\n  expected: ${expectedInput}\n  actual:   ${actualInput ?? '<missing>'}`);
  }
  if (actualOutput !== expectedOutput) {
    drifted = true;
    report.push(`[drift] OperatorMethodOutputMap["${entry.methodId}"]\n  expected: ${expectedOutput}\n  actual:   ${actualOutput ?? '<missing>'}`);
  }

  if (!CHECK_ONLY) {
    console.log(`  "${entry.methodId}": ${expectedInput};    // -> OperatorMethodInputMap`);
    console.log(`  "${entry.methodId}": ${expectedOutput};    // -> OperatorMethodOutputMap`);
  }
}

if (drifted) {
  console.error(report.join('\n\n'));
  console.error(
    `\n[check-foundation-io-types] drift detected across ${report.length} entr${report.length === 1 ? 'y' : 'ies'} — ` +
      'run `bun run scripts/generate-foundation-io-entries.ts` to re-render foundation-client-types.ts ' +
      'from the method-catalog schemas.',
  );
  if (CHECK_ONLY) process.exit(1);
} else {
  console.log(`[check-foundation-io-types] all ${ENTRIES.length * 2} entries (${ENTRIES.length} methods x input/output) match their source schemas.`);
}
