// NIT-05: Wildcard policy for `platform/types/index.ts` barrel.
//
// This barrel intentionally uses `export *` from each domain module rather than
// named re-exports. Reasoning:
//
// - `daemon-error-contract.js`, `errors.js`, `foundation-contract.js`, `tools.js`:
//   stable and tightly-curated source files; their public exports are reviewed at
//   edit time and any addition is intentional. Wildcards keep the barrel diff
//   focused on real changes (the underlying file changes) rather than barrel churn.
//
// - `generated/foundation-client-types.js`: the only generated module here. It is
//   regenerated by `bun run refresh:contracts` from the contract source-of-truth.
//   New symbols added by regen are intentional public surface (the contract just
//   added them). The api.md diff (`api:check`) catches accidental leaks at CI time;
//   a named-only barrel here would only shift detection from CI to PR review.
//
// If a future regen begins adding accidental internal types, switch this line to
// a named re-export and enumerate the intended public set.
export * from './daemon-error-contract.js';
export * from './errors.js';
export * from './foundation-contract.js';
export * from './generated/foundation-client-types.js';
export * from './tools.js';
